import type { Metadata } from 'next';
import {Header,Footer} from '../components';
import StandardContactForm from './StandardContactForm';
import './trusted-contact.css';
import './mobile-containment.css';
export const metadata:Metadata={title:'Contact Outsourced Service | Plan Your Outsourced Team',description:'Tell us which workflows, service roles, tools, and review steps your outsourced team needs. Start a practical Philippines staffing conversation.',alternates:{canonical:'https://outsourcedservice.com/contact-us'},robots:{index:true,follow:true},openGraph:{title:'Plan Your Outsourced Service Team',description:'Bring the workflow, tools, schedule, and approval points. Leave with a clearer outsourced service role brief.',url:'https://outsourcedservice.com/contact-us',type:'website',images:[{url:'/aug19-heroes/service-delivery-launch-readiness-review.webp',width:1200,height:675,alt:'A service delivery team reviewing a launch plan'}]}};
const booking='https://go.oncehub.com/StealthAgentsTeam';
const cards=[['The work lane','List recurring requests, source material, and a finished example your reviewer trusts.'],['The systems','Name the inboxes, queues, documents, and access that should remain restricted.'],['The handoff','Explain who assigns work, answers exceptions, and records completion or blockers.'],['The review','Choose the fields or sample your manager can check before expanding scope.']];
const capabilities=['Customer request intake and routing','Recurring administrative coordination','CRM and record maintenance','Reporting preparation and QA','Document collection and indexing','Calendar and follow-up support','Knowledge base maintenance','Back-office queue handoffs'];
export default function ContactUsPage(){return <><Header/><main className="tc-page"><section className="tc-hero" id="contact-form"><div className="tc-hero-grid"><div className="tc-copy"><p className="tc-kicker">Outsourced service, clearly scoped</p><h1>Build an outsourced team around work you can explain and review</h1><p className="tc-lead">Tell us what happens every week, which tools hold the work, and where your team still needs to approve a decision. We’ll use that context to discuss a practical Philippines-based service role.</p><ul><li>Start with one real workflow, not a generic job title</li><li>Define access, handoffs, and owner-only decisions</li><li>Agree on what a reviewable result should contain</li></ul><a className="tc-book" href={booking} target="_blank" rel="noopener noreferrer">Choose a consultation time ↗</a></div><StandardContactForm endpoint="/api/contact" encoding="form"/></div></section>
<section className="tc-section tc-prepare"><div className="tc-shell"><p className="tc-kicker">A useful first conversation</p><h2>Bring four pieces of operating context</h2><div className="tc-cards">{cards.map((c,i)=><article key={c[0]}><b>0{i+1}</b><h3>{c[0]}</h3><p>{c[1]}</p></article>)}</div></div></section>
<section className="tc-about"><div className="tc-image"><img src="/aug19-heroes/service-delivery-launch-readiness-review.webp" width="1200" height="675" alt="Service delivery specialists reviewing a workflow launch checklist"/><div><span>Plan</span><span>Test</span><span>Review</span></div></div><div><p className="tc-kicker">The team behind the conversation</p><h2>About Stealth Agents</h2><p className="tc-trust">Stealth Agents works with over 35+ different industries. We&apos;re featured on Forbes as the top rated virtual assistant company.</p><p>That broad experience is a starting point, not a substitute for discovery. Your consultation should still identify the actual queue, schedule, safeguards, and approvals that shape the role.</p><a href="https://stealthagents.com/" target="_blank" rel="noopener noreferrer">Powered by Stealth Agents ↗</a></div></section>
<section className="tc-section tc-cap"><div className="tc-shell"><p className="tc-kicker">Scope before staffing</p><h2>Workflows an outsourced service brief can cover</h2><p>Every lane still needs buyer-owned rules, training, access decisions, and review.</p><div className="tc-checks">{capabilities.map(x=><span key={x}>✓ {x}</span>)}</div></div></section>
<section className="tc-section tc-process"><div className="tc-shell"><p className="tc-kicker">What happens next</p><h2>From task list to a testable service lane</h2><div className="tc-steps"><article><b>1</b><div><h3>Describe the queue</h3><p>We start with frequency, volume, tools, hours, examples, and the people who own decisions.</p></div></article><article><b>2</b><div><h3>Shape the role</h3><p>Separate repeatable work from exceptions and identify the support a specialist needs.</p></div></article><article><b>3</b><div><h3>Plan the first review</h3><p>Know what will be checked and who can approve the next lane before scope grows.</p></div></article></div></div></section>
<section className="tc-close"><div><p className="tc-kicker">Ready when the workflow is</p><h2>Turn recurring work into a clearer outsourced service brief.</h2><p>Use the consultation form or choose a time that works for your team.</p></div><div><a href="#contact-form">Book My Free Consultation</a><a href={booking} target="_blank" rel="noopener noreferrer">Open the booking calendar ↗</a></div></section></main><Footer/></>}
