export const august31BlogPosts = ([
  ['virtual-assistant-monday-priority-brief','A Monday Priority Brief for Your Virtual Assistant','A short Monday brief settles priorities, deadlines, and escalation rules before routine work competes for attention.', ['Open with the outcome needed by Friday. For each priority, name the source record, deadline, and person who can answer questions.','Ask the assistant to reply with their planned order of work. That check exposes missing access and unclear deadlines early.','Close the week against the same brief. Record what finished, what moved, and which instruction needs a better example next Monday.']],
  ['delegated-inbox-label-system','Build an Inbox Label System an Assistant Can Actually Use','A small label set helps an inbox assistant sort messages without hiding urgent work inside a complicated taxonomy.', ['Base labels on actions such as Draft, Owner Decision, Waiting, and Filed. Add one normal example and one edge case for each.','Route account security, legal notices, payments, and angry customer messages to an owner-review lane. The assistant can identify them without deciding the response.','Review a sample after three days. Merge labels people confuse and add a rule only when a real message proves the gap.']],
  ['virtual-assistant-calendar-conflict-rules','Calendar Conflict Rules for a Virtual Assistant','Written conflict rules help an assistant protect focus time while important tradeoffs stay with the executive.', ['List meetings the assistant may move, plus protected events, travel buffers, and personal blocks that should never change silently.','When two protected items collide, the assistant should present the options, affected people, and latest decision time. The executive chooses.','Review repeated clashes once a week and update the rulebook when the same judgment call appears twice.']],
  ['crm-cleanup-work-sample','How to Design a CRM Cleanup Work Sample','A controlled work sample shows whether a candidate can follow field rules, document uncertainty, and avoid destructive edits.', ['Use fictional or safely redacted test records with duplicates, missing fields, stale notes, and one item that should remain untouched.','Score accuracy, traceability, questions raised, and changes outside the brief. Keep all hiring exercises out of production systems.','Remove test access after the exercise and retain the score against the same written rubric used for every candidate.']],
  ['assistant-document-naming-convention','A Document Naming Convention for Delegated Work','Predictable filenames help an assistant save drafts, approved copies, and source material where teammates can find them.', ['Choose fields that answer retrieval questions: project, purpose, relevant date, and status. Avoid codes that require a decoder.','Show examples for a draft, approved file, and archived item. State who may mark a document approved and where obsolete copies go.','Ask someone who did not create the file to find it. If search depends on insider knowledge, simplify the convention.']],
  ['virtual-assistant-blocker-log','Use a Blocker Log Without Creating More Admin Work','A compact blocker log records stalled work, the needed decision, and the next check-in time.', ['Log a task only when work cannot continue without access, information, or a decision. Routine progress stays in the task system.','Record the task link, blocking condition, owner, date raised, and next action. Use a separate urgent channel for security or customer harm.','Close each blocker with the decision or link that resolved it. Repeated blockers point to an SOP or access problem.']],
  ['customer-follow-up-approval-matrix','Customer Follow-Up Approval Matrix for Assistants','An approval matrix separates routine follow-up from promises, refunds, and sensitive cases that need an internal owner.', ['Group messages by the decision they contain. Approved status updates may be routine; refunds and contract changes should route to an owner.','For each group, specify the template, response window, system of record, and escalation contact. Include boundary examples.','Sample sent messages weekly. Check the classification and revise the matrix when a real case exposes ambiguity.']],
  ['assistant-end-of-day-handoff','An End-of-Day Handoff That Takes Five Minutes','A brief handoff keeps unfinished work visible across time zones without rewriting the task board.', ['Cover only what changes the next person\'s work: completed items, active blockers, and anything due before the assistant returns.','Point to the task system instead of duplicating every status. Name the owner and decision time for customer commitments and access concerns.','If the handoff regularly takes more than five minutes, inspect the records. The team may be maintaining two competing reports.']],
  ['virtual-assistant-permission-review','Run a Monthly Permission Review for Virtual Assistants','A monthly review checks whether each account still matches current work and removes access with no purpose.', ['List active accounts and roles, then connect every permission to a current task and internal owner.','Check shared credentials, unused admin roles, inactive integrations, and missing multi-factor authentication. Record each change.','Review upcoming role changes too. Access can be widened later when a documented task requires it.']],
  ['sop-change-request-template','An SOP Change Request Template for Assistant Teams','A lightweight request lets assistants flag outdated instructions without quietly rewriting an approved process.', ['Ask for the current step, observed problem, one real example, and proposed wording. Separate today\'s exception from a permanent edit.','Name the approver and retain a revision note so the team can tell which version applies and why it changed.','Review declined requests. They can reveal missing examples or a rule that only experienced teammates understand.']],
  ['assistant-weekly-quality-sample','Choose a Fair Weekly Quality Sample for Assistant Work','A mixed weekly sample shows routine accuracy and exception handling better than a review of only easy tasks.', ['Select work across the week and include ordinary items plus exceptions. Score against a short written checklist.','Record the source, rule applied, error, and correction owner. Treat repeated ambiguity as a possible instruction problem.','Keep the sample small enough to repeat weekly. A stable habit produces better evidence than an occasional large audit.']],
  ['virtual-assistant-offboarding-checklist','Virtual Assistant Offboarding: A Same-Day Checklist','A same-day checklist closes accounts, transfers work, and records ownership during a departure.', ['Remove access at the agreed time, revoke sessions, rotate shared secrets, and transfer files, calendars, and automations.','Move open work to named teammates. Follow the contract and internal policy for equipment and retained data.','Verify the highest-risk systems after access closes, then use any gap to improve the next onboarding inventory.']],
] as Array<[string,string,string,string[]]>).map(([slug,title,excerpt,body],index)=>({slug,title,excerpt,body,minutes:7+(index%4),published:'2026-08-31',image:`https://images.unsplash.com/photo-${['1497215728101-856f4ea42174','1557200134-90327ee9fafa','1506784983877-45594efa4cbe','1551288049-bebda4e38f71','1456324504439-367cee3b3c32','1484480974693-6ca0a78fb36b','1521737711867-e3b97375f902','1522071820081-009f0129c71c','1563013544-824ae1b704d3','1516321318423-f06f85e504b3','1454165804606-c3d57bc86b40','1551836022-d5d88e9218df'][index]}?auto=format&fit=crop&w=1200&q=80`,citations:['https://www.nist.gov/cyberframework','https://www.cisa.gov/secure-our-world/use-strong-passwords']}));

export const august31ResearchPosts = ([
  ['delegation-queue-sampling-method','A Sampling Method for Reviewing Delegated Work Queues','This note explains how to select a repeatable mixed sample without treating a small review as proof about every task.',['Question: how can a manager inspect delegated work without reviewing the entire queue?','Method: select items across the period, including ordinary work, exceptions, and one item chosen independently of the assistant. Record the rule before scoring.','Interpretation: the sample describes only reviewed items. Repeated errors justify a wider check; a clean small sample does not establish that every item was correct.']],
  ['virtual-assistant-access-inventory-method','Method Note: Building a Virtual Assistant Access Inventory','A role-based inventory connects every account to current work, an internal owner, and a removal step.',['Question: what evidence shows that assistant access still matches the job?','Method: enumerate accounts, then map each role to a current task, owner, authentication method, and offboarding action.','Limit: the inventory can miss informal credential sharing, so reconcile it with team checks and rotation records. Remove permissions with no documented purpose.']],
  ['handoff-delay-observation-framework','An Observation Framework for Handoff Delays','This framework separates waits caused by ownership, missing information, access limits, and ordinary queue timing.',['Question: why does work stall between an assistant and an internal owner?','Method: record the handoff time, requested decision, owner, source links, first response, and restart time. Classify the first blocking condition.','Interpretation: missing-owner clusters suggest a routing problem. Missing-information clusters may point to the brief. These categories describe workflow, not motivation.']],
  ['sop-revision-evidence-standard','An Evidence Standard for SOP Revisions','A modest evidence standard distinguishes a one-off exception from an instruction that repeatedly fails.',['Question: when should an observed problem produce a permanent SOP revision?','Method: retain the applicable version, source record, action, result, and reviewer decision. Compare multiple occurrences when risk permits.','Limit: frequency does not determine importance. A rare security failure may demand immediate action. Keep approval and version control with the process owner.']],
  ['assistant-workload-capacity-diary','A Work Diary Method for Estimating Assistant Capacity','A short diary shows where time goes while keeping observed effort separate from a permanent productivity target.',['Question: how much recurring work fits into the current role and process?','Method: for a limited period, record task category, work time, waiting, rework, completed units, and unusual outages or training.','Interpretation: calculate ranges by category and keep waiting separate. One week is not a universal benchmark. Recheck when tools or duties change.']],
] as Array<[string,string,string,string[]]>).map(([slug,title,excerpt,body],index)=>({slug,title,excerpt,body,published:'2026-08-31',image:`https://images.unsplash.com/photo-${['1552664730-d307ca884978','1563986768609-322da13575f3','1521737711867-e3b97375f902','1516321318423-f06f85e504b3','1454165804606-c3d57bc86b40'][index]}?auto=format&fit=crop&w=1200&q=80`,citations:['https://www.nist.gov/cyberframework','https://www.cisa.gov/secure-our-world/use-strong-passwords']}));
