type ResearchPost={slug:string;title:string;excerpt:string;published:string;thumbnail:string;body:readonly string[];headlineStat:string;methodology:string;sources:readonly {label:string;url:string}[];related:readonly string[];faq:readonly {question:string;answer:string}[]};

const sourceSets={
 operations:[
  {label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {label:'ISO 9001 Quality Management',url:'https://www.iso.org/iso-9001-quality-management.html'},
  {label:'U.S. National Archives Records Management',url:'https://www.archives.gov/records-mgmt'},
  {label:'FTC Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business'}
 ],
 customer:[
  {label:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {label:'W3C WCAG 2.2',url:'https://www.w3.org/TR/WCAG22/'},
  {label:'U.S. National Archives Records Management',url:'https://www.archives.gov/records-mgmt'}
 ]
} as const;

type Config={topic:string;unit:string;decision:string;exception:string;cohort:string;finding:string;limit:string;measure:string;sourceNote:string;question:string;answer:string;sources:readonly {label:string;url:string}[]};

const researchBody=(c:Config):readonly string[]=>[
 `This study examines ${c.topic} as a bounded support-service question. Its unit of analysis is ${c.unit}, not a whole business, workforce, or customer population. That distinction matters because a carefully recorded administrative event can show what happened to one item without proving that every item received the same treatment. The research question is whether the work leaves enough evidence for an accountable owner to review the result and its uncertainty.`,
 `The first finding is that the item needs a stable identity before anyone can measure its handling. ${c.unit} should have an originating reference, a received or created time, a current state, and an explicit owner. A descriptive label alone is weak evidence: two records can look similar while carrying different permissions, commitments, or deadlines. Identity is therefore a prerequisite to both service quality and useful reporting.`,
 `The second finding concerns source fidelity. A support specialist can prepare a record from an approved source, but preparation should remain distinguishable from invention, interpretation, or approval. ${c.finding} If the source is incomplete, the honest output is a visible exception or a request for clarification. Filling the field with a plausible guess may improve apparent completion while making the next decision less reliable.`,
 `The decision boundary should be written beside the work. ${c.decision} The support lane can collect, compare, label, and route evidence when those actions have an observable rule. It should not make a material promise, alter a policy, or convert an unresolved question into a final answer merely because the queue is old. Authority is part of the record, not an assumption held in one person’s memory.`,
 `Exceptions deserve their own classification. ${c.exception} A useful exception note records the observed condition, the source checked, the time of the check, the consequence if nothing changes, and the person who must decide. “Needs attention” does not provide enough information for a later reviewer to reproduce the issue. A small vocabulary of exception types can make patterns visible without pretending that every case has the same cause.`,
 `The relevant cohort must be defined before a rate is calculated. ${c.cohort} Mixing these populations can create a misleading trend because an older item has had more opportunity to change than a newly received one. The report should state the inclusion rule, the start and end dates, exclusions, and whether the denominator is items received, items closed, or items checked.`,
 `Timing is more than a timestamp displayed for convenience. Received, acknowledged, updated, approved, and completed may be different events. For this topic, the owner should decide which interval matters and preserve the other dates when they explain a delay or correction. A duration calculated from the wrong pair of events can look precise while answering a different question from the one the business actually cares about.`,
 `A second control is field-level provenance. The record should show which value came from which source and whether the value was copied, reconciled, or reviewed. This is especially important when a source contains several versions or when two systems disagree. A short source reference is often more useful than a long narrative because it lets another person inspect the underlying evidence without reconstructing the entire exchange.`,
 `Privacy and security narrow the information that should be retained. The cited NIST and FTC guidance supports collecting only what the task needs, controlling access, and protecting sensitive information through the lifecycle. A support record should not become a convenient duplicate of an entire customer file. The reviewer should be able to answer why each retained field exists and which role needs to see it.`,
 `Quality is not identical to speed. A quick update that preserves the wrong source, omits a conflict, or routes the wrong owner can create more work downstream. ISO 9001’s process perspective is useful here as a vocabulary for inputs, activities, outputs, and evidence, but it does not certify this service lane or guarantee an outcome. The owner must define what “fit for release” means in the actual context.`,
 `A practical sample should include ordinary items and difficult items. Select a named number of records from the cohort, include at least one exception category, and ask a reviewer who did not perform the work to follow the evidence trail. The sample cannot prove universal performance, but it can reveal an undefined field, an unstable source, a duplicate identity, or an escalation path that nobody can use consistently.`,
 `The sample result should report both successes and unresolved cases. ${c.measure} A percentage without its denominator, date range, and exception treatment is not a reproducible finding. Report counts first, then any rate, and keep the raw exception categories available for inspection. This allows the owner to decide whether a change improved the work or merely changed what was counted.`,
 `Interpretation must be bounded. A high completion count may mean that the lane is well controlled, that difficult items were excluded, or that “complete” was defined too loosely. A slower cohort may include more approvals or more missing inputs. The evidence can support a narrow statement about the sampled records; it cannot, by itself, establish causation, universal suitability, or a promise about future volume.`,
 `The handoff should make the next action unambiguous. It should identify the item, current state, evidence link, open question, owner, due condition, and any privacy restriction. A polished summary that hides the unresolved decision is less useful than a plain handoff that says exactly what remains unknown. The receiving person should not need a private conversation with the preparer to understand the record.`,
 `Change history matters when an item is corrected. Preserve the prior value or source reference when it explains why the correction occurred, while avoiding unnecessary duplication of sensitive data. The history should show who prepared the change, who approved it when approval was required, and when it took effect. A later reviewer can then distinguish a correction from a new event and avoid counting both as separate outcomes.`,
 `The method has important limits. This is a comparative desk review of the named public frameworks and records guidance, not a field experiment on a particular provider or organization. The sources describe principles rather than a local operating result. They do not replace an agreement, a privacy assessment, professional advice, or a decision by the person who owns the underlying account, policy, or commitment.`,
 `A safe pilot begins with a narrow lane and a known denominator. Define the source systems, permitted fields, owner roles, exception categories, review sample, and stop condition before increasing volume. If reviewers disagree about the same record, pause expansion and resolve the field definition or authority rule. Repeating a vague process more quickly makes the ambiguity harder to detect, not easier to manage.`,
 `For a buyer evaluating recurring support, the relevant test is traceability rather than impressive activity. Can an owner identify the original request, see the transformation, understand the remaining uncertainty, and approve the action that requires authority? Can a second reviewer reproduce the finding from the retained evidence? If not, the lane needs a narrower scope or a better record design before its output is used for a consequential decision.`,
 `The conclusion is deliberately modest: ${c.limit} Good administration makes evidence easier to inspect and exceptions easier to route; it does not remove the need for judgment. A support specialist can keep routine records moving while the accountable owner retains responsibility for commitments, policy interpretation, sensitive decisions, and changes that affect another party.`,
 `The resulting scorecard should therefore include the cohort, denominator, dates, source coverage, exception counts, correction counts, and owner decisions. It should also state what was not measured. Those omissions are not an embarrassment; they are part of the boundary of the finding. A report that names its limits is more useful for planning the next sample than one that presents an unexplained single score.`,
 `This research supports a repeatable division of labor: the service lane prepares observable evidence, the reviewer tests a sample, and the accountable owner decides where meaning, risk, policy, or commitment is involved. That division preserves speed for routine work without pretending that a prepared record is a substitute for authority. The next improvement should be driven by recurring exceptions and disagreement, not by volume alone.`
];

const make=(slug:string,title:string,excerpt:string,headlineStat:string,c:Config,related:readonly string[]):ResearchPost=>({
 slug,title,excerpt,published:'2026-08-14',thumbnail:'/research-thumbnails/research-batch-2026-08-10.svg',body:researchBody(c),headlineStat,methodology:'Methods note: comparative desk review of the authoritative sources listed below. They provide general records, privacy, security, accessibility, and quality principles; they do not measure a provider or guarantee a business result.',sources:c.sources,related,faq:[{question:c.question,answer:c.answer}]
});

// Every campaign record binds the publication date directly to its own object.
// Do not replace these literals with a batch-level date or infer them in the loader.
const generatedAugust14ResearchPosts:readonly ResearchPost[]=[
 make('philippines-returns-exception-evidence-research','Philippines returns administration: exception evidence research','A bounded study of return records, source evidence, and approval boundaries for recurring operations support.','8 evidence fields for one return exception',{topic:'returns administration for customer and order records',unit:'one return request matched to one order and its approved policy source',decision:'The accountable owner confirms eligibility, refund authority, and any policy exception.',exception:'A missing order reference, conflicting condition, duplicate request, or unclear approval path must be routed before a commitment is made.',cohort:'New return requests, reopened cases, and historical corrections should be reported as separate cohorts.',finding:'A return record should preserve the request, order identity, policy version, item condition evidence, and decision status.',limit:'a return queue can show whether records were prepared and routed; it cannot establish that a policy is fair or that a customer outcome was appropriate without owner review.',measure:'Count requests with a valid source, requests routed for exception, requests awaiting owner decision, and records corrected after review.',sourceNote:'',sources:sourceSets.customer,question:'What should a return record prove?',answer:'It should connect the request to the order, policy source, evidence checked, current status, and owner decision.'},['philippines-order-status-evidence-research']),
 make('philippines-appointment-change-record-research','Philippines appointment coordination: change-record research','Research on preserving appointment requests, confirmations, time zones, and owner approval when schedules change.','7 checks for one appointment change',{topic:'appointment coordination and schedule-change administration',unit:'one appointment event with one requested or confirmed change',decision:'The designated owner confirms material time, attendee, location, and cancellation decisions.',exception:'A time-zone conflict, missing confirmation, duplicate booking, or request from an unclear authority must be escalated.',cohort:'New bookings, reschedules, cancellations, and no-show follow-ups should not be collapsed into one completion rate.',finding:'A schedule record should distinguish requested time, confirmed time, source calendar, attendee response, and the person authorized to approve a change.',limit:'calendar evidence can establish what was requested and recorded, but it cannot prove attendance, satisfaction, or the reason for a missed appointment.',measure:'Report confirmed changes, unresolved conflicts, duplicate events, and owner-approved exceptions by event type and local date.',sourceNote:'',sources:sourceSets.operations,question:'Which appointment times should be retained?',answer:'Retain the requested, confirmed, and changed times with their time-zone context and source reference.'},['philippines-itinerary-change-evidence-research-evidence-study']),
 make('philippines-order-status-evidence-research','Philippines order-status support: evidence and aging research','A study of status updates that keeps source timing, customer-facing wording, and unresolved order exceptions distinct.','6 fields for one defensible status update',{topic:'order-status support for recurring customer inquiries',unit:'one customer inquiry linked to one order-status source record',decision:'The order owner approves commitments, compensation, and explanations that go beyond the approved status source.',exception:'A stale source, partial shipment, address conflict, or missing carrier event must be visible as an exception.',cohort:'New inquiries, repeat inquiries, and orders already in an exception queue need separate aging views.',finding:'A status update is more defensible when it names the source event, source time, current state, next check, and uncertainty instead of repeating a generic label.',limit:'an updated status record does not prove delivery, customer understanding, or carrier performance; it records the evidence available at the check time.',measure:'Count inquiries with a current source event, inquiries awaiting a source update, and cases escalated for a commitment or exception.',sourceNote:'',sources:sourceSets.customer,question:'What makes an order status update traceable?',answer:'A source event, order identity, check time, current state, and clearly stated next action.'},['philippines-returns-exception-evidence-research']),
 make('philippines-onboarding-readiness-evidence-research','Philippines customer onboarding: readiness evidence research','How onboarding support can distinguish received information, verified readiness, and decisions still owned by the client team.','9 fields for one onboarding readiness record',{topic:'customer onboarding readiness administration',unit:'one onboarding requirement for one customer and one defined start period',decision:'The customer owner approves readiness, access, exceptions, and any change to the agreed sequence.',exception:'An absent input, conflicting stakeholder instruction, sensitive document, or missed dependency must be routed with its source.',cohort:'New implementations, paused implementations, and reopened requirements should be measured separately.',finding:'Readiness is not the same as a filled field: the record should identify the requirement, source, verifier, dependency, and approval state.',limit:'a readiness checklist can show evidence collected for a defined requirement; it cannot prove successful adoption or customer value.',measure:'Report requirements received, verified, blocked, awaiting owner decision, and reopened after an earlier completion state.',sourceNote:'',sources:sourceSets.operations,question:'Does a completed field prove onboarding readiness?',answer:'No. Readiness also depends on source validity, dependencies, owner approval, and the defined start condition.'},['philippines-training-completion-verification-evidence-research-evidence-study']),
 make('philippines-knowledge-article-freshness-research','Philippines knowledge-base maintenance: freshness evidence research','Research on reviewing operational knowledge without confusing a recent edit with an approved or accurate instruction.','6 evidence checks for one knowledge article',{topic:'knowledge-base maintenance for customer and operations information',unit:'one knowledge article reviewed against one named source and review period',decision:'The content owner approves substantive meaning, policy language, and publication of a changed instruction.',exception:'A stale source, conflicting instruction, missing owner, or accessibility concern must stop routine release.',cohort:'New articles, scheduled reviews, urgent corrections, and retired articles should remain distinct populations.',finding:'Freshness is a property of the review evidence and source date; it is not proof that an instruction remains correct in every situation.',limit:'a maintenance record can show that an article was checked against a source, but it cannot guarantee reader comprehension or real-world compliance.',measure:'Count articles with a current source, articles needing owner review, corrections after publication, and items retired for lack of a valid owner.',sourceNote:'',sources:sourceSets.customer,question:'What does freshness actually show?',answer:'It shows when an article was checked against a named source; it does not by itself prove accuracy or reader success.'},['philippines-web-content-accessibility-research']),
 make('philippines-invoice-intake-evidence-research','Philippines invoice administration: intake and exception research','A source-backed study of invoice intake records that separates transcription from coding, approval, and payment authority.','8 fields for one invoice exception',{topic:'invoice intake and administrative record preparation',unit:'one invoice matched to one approved supplier and one receiving or service source',decision:'The authorized finance owner approves coding, payment, disputes, and any exception to the control rule.',exception:'A duplicate invoice, mismatched supplier, absent receipt, changed bank detail, or unclear coding must be held for review.',cohort:'New invoices, resubmissions, credit notes, and historical corrections should not share one aging denominator.',finding:'An intake record should preserve the document identity, supplier source, received date, matching evidence, coding status, and approval state.',limit:'intake evidence can show what was received and matched; it cannot authorize payment or establish that a charge is commercially correct.',measure:'Report invoices with complete source evidence, invoices held for exception, duplicates identified, and owner decisions by defined period.',sourceNote:'',sources:sourceSets.operations,question:'What is the handoff boundary for invoice support?',answer:'Support can prepare and match evidence; the authorized finance owner retains coding, payment, and dispute decisions.'},['philippines-supplier-record-freshness-evidence-research-evidence-study']),
 make('philippines-support-queue-aging-research','Philippines customer-support queue: aging and escalation research','Research on queue records that treats age, priority, source quality, and escalation as separate dimensions of support work.','7 fields for one reviewable support case',{topic:'customer-support queue administration and escalation',unit:'one support case with one customer request, source thread, and next action',decision:'The support owner approves refunds, policy exceptions, sensitive responses, and commitments outside approved guidance.',exception:'A complaint, privacy concern, unclear identity, missing context, or repeated unresolved contact must be escalated.',cohort:'New cases, reopened cases, follow-ups awaiting a customer, and cases awaiting an internal owner should be reported separately.',finding:'Queue age is only meaningful when the clock, pause conditions, priority rule, and current owner are explicit.',limit:'a queue report can describe routing and response activity, but it cannot establish customer satisfaction or resolution quality without a separate outcome measure.',measure:'Report cases by state and clock condition, then show exception categories, owner waits, reopened cases, and sampled response quality.',sourceNote:'',sources:sourceSets.customer,question:'Why separate queue states?',answer:'A new case, a customer wait, and an internal owner wait have different causes and should not share one aging interpretation.'},['philippines-mailbox-handoff-evidence-research-evidence-study']),
 make('philippines-capacity-appointment-research','Philippines appointment capacity: evidence-led coordination research','A bounded study of appointment capacity records, buffers, conflicts, and the limits of interpreting schedule utilization.','5 source fields for one capacity decision',{topic:'appointment-capacity coordination for recurring service requests',unit:'one available or reserved appointment slot in one local time period',decision:'The schedule owner approves capacity rules, buffers, priority changes, and commitments to external parties.',exception:'A conflicting calendar, unavailable resource, missing duration, or overbooked period must be routed before confirmation.',cohort:'Published availability, provisional holds, confirmed appointments, and cancelled slots should be analyzed separately.',finding:'Capacity is a relationship between a slot, a resource, a duration assumption, and a confirmed demand record; an empty calendar cell is not automatically available capacity.',limit:'a calendar sample can show recorded utilization under stated assumptions, but it cannot forecast demand or prove that a schedule is optimal.',measure:'Report slots by state, duration source, conflict type, cancellations, and owner-approved overrides for the defined period.',sourceNote:'',sources:sourceSets.operations,question:'What does an empty slot mean?',answer:'Only that no confirmed event is recorded there; availability still depends on resource, duration, buffers, and owner rules.'},['philippines-appointment-change-record-research']),
 make('philippines-service-review-sampling-research','Philippines service review sampling: evidence and limitation research','How a small review sample can expose recurring record problems without being presented as a universal performance claim.','6 fields for one defensible review sample',{topic:'service-quality review sampling for administrative support records',unit:'one sampled work item evaluated against a named criterion and source record',decision:'The service owner decides remediation, policy changes, and whether a sample supports a broader operational action.',exception:'An ambiguous criterion, missing source, disagreement between reviewers, or material error must be recorded separately.',cohort:'Routine samples, targeted samples, rechecks, and items selected after an incident have different selection effects.',finding:'A review result is interpretable only when the population, selection method, criterion version, reviewer, and disagreement treatment are visible.',limit:'a small or targeted sample can diagnose a control problem but cannot estimate general performance without a defensible sampling design.',measure:'Report sample size, population definition, selection rule, pass and exception counts, reviewer disagreements, and corrections made.',sourceNote:'',sources:sourceSets.operations,question:'What is the main sampling limitation?',answer:'A targeted or small sample can reveal issues but may not represent the wider population or predict future performance.'},['philippines-survey-cohort-quality-evidence-research-evidence-study']),
 make('philippines-data-entry-reconciliation-research','Philippines data-entry reconciliation: source and correction research','Research on entering recurring records while preserving source values, reconciliation logic, corrections, and owner decisions.','8 checks for one reconciled record',{topic:'data-entry and record reconciliation for recurring operations support',unit:'one destination record compared with one approved source record at a defined check time',decision:'The record owner approves material changes, source conflicts, and any interpretation that affects a customer or commitment.',exception:'A duplicate identity, missing source field, conflicting value, or unexplained manual override must be held for review.',cohort:'First entry, scheduled refresh, correction, and migration records should be tracked as separate work types.',finding:'Accuracy is not established by a matching-looking value alone; the reviewer needs the source, comparison rule, field scope, and correction history.',limit:'a reconciliation result can support confidence in a defined field comparison, but it cannot prove the source itself is true or current.',measure:'Report fields compared, fields changed, unresolved conflicts, duplicate identities, and post-review corrections by work type.',sourceNote:'',sources:sourceSets.customer,question:'What does reconciliation prove?',answer:'It proves that defined destination fields were compared with a named source under a stated rule; it does not prove the source is correct.'},['philippines-catalog-field-change-evidence-research-evidence-study'])
];

const august14CampaignRecords=[
 {slug:'philippines-returns-exception-evidence-research',published:'2026-08-14'},
 {slug:'philippines-appointment-change-record-research',published:'2026-08-14'},
 {slug:'philippines-order-status-evidence-research',published:'2026-08-14'},
 {slug:'philippines-onboarding-readiness-evidence-research',published:'2026-08-14'},
 {slug:'philippines-knowledge-article-freshness-research',published:'2026-08-14'},
 {slug:'philippines-invoice-intake-evidence-research',published:'2026-08-14'},
 {slug:'philippines-support-queue-aging-research',published:'2026-08-14'},
 {slug:'philippines-capacity-appointment-research',published:'2026-08-14'},
 {slug:'philippines-service-review-sampling-research',published:'2026-08-14'},
 {slug:'philippines-data-entry-reconciliation-research',published:'2026-08-14'}
] as const;

export const august14ResearchPosts:readonly ResearchPost[]=august14CampaignRecords.map(record=>({
 ...generatedAugust14ResearchPosts.find(post=>post.slug===record.slug)!,
 slug:record.slug,
 published:record.published
}));
