type ResearchPost = {slug:string;title:string;excerpt:string;published:string;thumbnail:string;body:readonly string[];headlineStat:string;methodology:string;sources:readonly {label:string;url:string}[];related:readonly string[];faq:readonly {question:string;answer:string}[]};
const sources=[
 {label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {label:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
 {label:'FTC data security guidance',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business'},
 {label:'ISO 9001 quality management overview',url:'https://www.iso.org/iso-9001-quality-management.html'},
 {label:'U.S. National Archives records management',url:'https://www.archives.gov/records-mgmt'},
 {label:'W3C Web Content Accessibility Guidelines',url:'https://www.w3.org/TR/WCAG22/'}
];
const body=(subject:string,unit:string,angles:readonly string[])=>[
 `This research examines ${subject} as a bounded service question. The unit of analysis is ${unit}. A clean record can still hide a poor decision if its source, authority, or review period is unclear. The aim is to describe what a Philippines-based specialist can prepare, what an owner must decide, and what evidence a second reviewer should find. It is not a claim that a particular provider will produce a particular result.`,
 `The first finding concerns the source record. ${angles[0]} A source is useful only when its identity, capture date, scope, and relationship to the request remain visible. If a record cannot be located again, the later summary becomes an assertion rather than a checkable finding.`,
 `The second finding concerns the permitted transformation. ${angles[1]} A support lane may copy, classify, compare, or prepare information when the rule is explicit. It should stop when the task changes meaning, creates a commitment, or requires a judgment that belongs to the client owner.`,
 `The third finding concerns exceptions. ${angles[2]} An exception note should state the observed condition, source used, date checked, and person who must decide. That detail is more useful than a status label such as complete, because the label does not explain what remains uncertain.`,
 `The fourth finding concerns access. ${angles[3]} NIST privacy and security guidance supports collecting only what the task needs and giving access to the systems and fields required for that task. The work record should never contain passwords, secrets, or unnecessary personal details.`,
 `The fifth finding concerns timing. ${angles[4]} A period must be named when the work depends on freshness, due dates, response windows, or a reporting cut-off. A daily queue, weekly report, and historical correction are different cohorts. Combining them makes an apparent improvement or defect difficult to interpret.`,
 `Quality review should use a defined sample rather than a general impression. Inspect ${unit} across the same period, record the number checked, and preserve examples of acceptable work and defects. A small sample cannot estimate every outcome, but it can reveal unclear fields, recurring omissions, and escalation rules that fail in practice.`,
 `The owner also needs a release boundary. ${angles[5]} ISO 9001's process approach is relevant because the work has an input, action, output, and evidence that the output met the agreed condition. The standard does not certify this service model; it supplies a useful vocabulary for repeatable checks.`,
 `Keep records and interpretation separate. The record says what was received or observed. Interpretation explains what that may mean. The decision chooses an action. Separating those layers prevents a prepared note from being mistaken for approval and lets a reviewer challenge the conclusion without losing the evidence.`,
 `The sources have limits. They discuss security, privacy, quality, records, and accessibility at a general level. They do not measure a Philippines-based service team on this particular task, replace a contract, or provide local legal advice. These proposed controls are hypotheses to test on the owner's records.`,
 `A sensible pilot includes ordinary work and at least one exception period. Define start and end dates, keep the initial scope narrow, and ask a different reviewer to reproduce a sample from the source links. If the reviewer needs private context or verbal explanation, revise the field definitions before expanding the queue.`,
 `The conclusion is specific: ${angles[6]} Success should be judged by traceable records, correct routing, visible exceptions, and an owner decision where authority is required. Speed or volume alone cannot show whether the underlying work was safe, complete, or suitable for the next person who relies on it.`,
 `For a buyer planning recurring support, the practical question is whether this task has a stable input, an observable finish line, a reviewable sample, and a named person for exceptions. When those conditions are absent, narrow the request and clarify ownership instead of inferring a rule from an incomplete record.`,
 `A second reviewer should be able to follow the work from request to source to prepared result. That means retaining the original reference, the field or item changed, the check performed, and the unresolved question. This evidence makes correction possible without asking the specialist to reconstruct a prior conversation.`,
 `The research therefore supports a modest operating claim. Clear boundaries can make routine administration easier to inspect, while unclear authority remains a risk even when the work appears simple. Owners should test the proposed fields against real records, document exceptions, and revise the lane when a recurring ambiguity appears.`
];
const make=(c:{slug:string;title:string;excerpt:string;stat:string;subject:string;unit:string;angles:readonly string[];related:readonly string[];faq:readonly {question:string;answer:string}[]}):ResearchPost=>({slug:c.slug,title:c.title,excerpt:c.excerpt,published:'2026-08-13',thumbnail:'/research-thumbnails/research-batch-2026-08-10.svg',headlineStat:c.stat,body:body(c.subject,c.unit,c.angles),methodology:'Methods note: comparative desk review of NIST Cybersecurity Framework 2.0, NIST Privacy Framework, FTC data-security guidance, ISO 9001, U.S. National Archives records guidance, and W3C WCAG 2.2. These sources establish control principles, not provider performance or a guarantee for a client.',sources,related:c.related,faq:c.faq});
const A=(topic:string, noun:string, result:string, boundary:string, exception:string, access:string, period:string, owner:string, conclusion:string)=>[`
The source for ${topic} should identify the ${noun}, the requested result, the date checked, and the record from which each field came.`,
`For ${topic}, the specialist can prepare ${result}, but the client owner retains ${boundary}.`,
`An incomplete, conflicting, or stale record is an ${exception}; it should be routed with evidence rather than silently repaired.`,
`${access} Access should match the task and should not expose unrelated personal or commercial information.`,
`${period} The review must say which period was sampled, because current work and historical corrections are different populations.`,
`The owner should approve the release condition and the exception path. ${owner}`, `The bounded conclusion is that ${conclusion}`,
`A reviewer should be able to reproduce the result from the source, see what changed, and identify the person who accepted the exception.`,
`A useful sample includes both ordinary records and at least one difficult case. Record the sample size, defect type, correction, and unresolved question.`,
`This does not establish a legal, financial, security, or performance guarantee. It is an operating hypothesis to test against the owner's actual records.`];
const configs=[
 ['philippines-customer-account-update-research','Philippines customer account updates: identity and change evidence','Research on preparing routine customer account changes while keeping identity checks, authorization, and exceptions visible.','7 evidence fields for a customer account change','customer account updates','one requested account change compared with its approved source record','requested field and approved new value','identity and authorization approval','duplicate request or ownership conflict','The record should contain only fields needed for verification.','Requests received in one business week should be separated from older records reopened later.','The owner confirms identity, authority, and material changes.','the source reference, actor, timestamp, and exception owner travel with the update.',['philippines-crm-case-administration-research','philippines-customer-onboarding-data-entry-research'],['What must be verified first?','Match the request to the approved source and confirm the identity and authority behind the change.']],
 ['philippines-kpi-data-collection-research','Philippines KPI data collection: period and source controls','A research brief on collecting recurring KPI inputs without losing metric definitions, periods, or review ownership.','6 source fields for a reproducible KPI row','KPI data collection','one metric for one named reporting period','metric definition, unit, period, value, and extraction date','any change to a metric definition or denominator','missing period or changed denominator','Report access should cover named reports, not unrelated customer detail.','A calendar week, month, quarter, and rolling interval are separate reporting cohorts.','The metric owner approves definitions and explanations.','a scorecard makes the number reproducible before it is used to make a claim.',['philippines-reporting-qa-research','philippines-client-reporting-support-research'],['What makes a KPI row reproducible?','A definition, unit, source, period, calculation note, and reviewer status.']],
 ['philippines-training-record-maintenance-research','Philippines training records: completion and version evidence','Research on maintaining training records with course versions, attendance evidence, and owner-controlled exceptions.','5 identifiers for a defensible training record','training record maintenance','one learner-course record for one defined training period','learner, course version, required date, and completion evidence','waiving a requirement or declaring an exception acceptable','absent evidence or an outdated course version','Personnel access should be limited to records needed for administration.','Current required training must be separated from historical completions.','The responsible manager approves waivers and requirement changes.','a record distinguishes complete, pending evidence, expired, and awaiting decision.',['philippines-hr-administration-research','philippines-compliance-administration-research'],['Why record the course version?','A completion may not satisfy a current requirement if the course or policy changed.']],
 ['philippines-vendor-data-maintenance-research','Philippines vendor data maintenance: record freshness research','How recurring supplier-record maintenance can preserve source evidence, freshness dates, and approval boundaries.','6 freshness checks for a vendor record','vendor data maintenance','one vendor record reviewed during a named maintenance cycle','supplier, field checked, source document, and check date','accepting terms or deciding vendor suitability','expired document or conflicting address','Supplier access should be limited to information needed for maintenance.','Newly onboarded suppliers and quarterly refresh records are different cohorts.','The vendor owner decides acceptance, terms, and payment matters.','freshness proves a check occurred, not that a supplier remains suitable for every purpose.',['philippines-procurement-support-research','philippines-document-management-research'],['What is a useful freshness record?','The field, source, check date, checker, and unresolved discrepancy.']],
 ['philippines-project-dependency-research','Philippines project coordination: dependency and milestone evidence','Research on keeping project updates useful by separating milestone facts, dependencies, and owner decisions.','8 fields for a reviewable project dependency','project coordination','one milestone or dependency during one reporting period','milestone, expected date, evidence, dependency, and accountable owner','changing scope, deadlines, or commitments','blocked task or missing owner','Project access should match the role and exclude unrelated confidential material.','A current status report and a historical decision are different record types.','The project owner decides scope, timing, and commitment changes.','the next owner can see what changed, why it matters, and who decides the response.',['philippines-project-coordination-research','philippines-project-status-reporting-guide'],['What is a dependency?','A condition or deliverable owned by another party that affects a milestone.']],
 ['philippines-survey-response-research','Philippines survey administration: response-quality controls','A source-backed study of survey response records, missing data, and the limits on interpreting small samples.','7 checks before a survey summary is used','survey administration','one response or one defined response cohort','instrument version, channel, date, and required analysis fields','turning a small sample into a universal conclusion','duplicate response or sensitive disclosure','Identifying details should be separated from analysis fields where possible.','An open survey and a closed response cohort must not be combined without explanation.','The owner approves interpretation and privacy handling.','a summary states what the cohort shows and what it cannot establish.',['philippines-customer-feedback-research','philippines-market-research-support-research'],['What is the main limitation?','A response cohort may not represent everyone invited or the wider population.']],
 ['philippines-compliance-evidence-research','Philippines compliance administration: evidence-chain controls','Research on collecting compliance evidence while keeping legal or policy judgments with the accountable owner.','7 links in a traceable compliance evidence chain','compliance evidence administration','one requirement checked against one evidence item during one review period','requirement, evidence owner, version, coverage period, and location','interpreting a legal requirement or approving a conclusion','missing evidence or contradictory record','Compliance files may contain sensitive material and require restricted access.','Current cycle evidence and historical material should remain distinguishable.','The authorized owner makes the legal or policy judgment.','an evidence packet supports review without pretending that collection proves compliance.',['philippines-legal-administration-research','philippines-compliance-administration-research'],['Is collecting evidence the same as approving compliance?','No. Collection supports review; the authorized owner makes the judgment.']],
 ['philippines-product-data-change-research','Philippines product data support: catalog change evidence','How product-record support can preserve source validation, approval boundaries, and reversible change history.','8 checks for a product-record change','product data support','one product field change on one catalog record','product, field, old value, requested value, approval, and effective date','inventing attributes or approving a commercial claim','missing specification or unclear owner','Catalog access should exclude unrelated orders and customer data.','Requested, approved, applied, and verified dates should remain distinct.','The product owner approves claims and material changes.','the source, approval, applied value, and verification result are read together.',['philippines-product-listing-support-research','philippines-ecommerce-support-research'],['What should never be invented?','Product specifications, availability, claims, and fields without an approved source.']],
 ['philippines-email-triage-research','Philippines email management: triage and response evidence','Research on bounded inbox triage, privacy limits, and escalation for messages that carry decisions.','6 fields for a reviewable inbox handoff','email management','one incoming message grouped into one defined triage period','message identifier, sender context, received time, category, and next action','making commitments or answering sensitive matters without authority','missing attachment or suspicious request','Mailbox access should cover only the folders required for the role.','Unread aging and new daily intake should preserve the original received time.','The owner approves reply sets and sensitive escalations.','the next action and owner are visible, not merely a handled label.',['philippines-inbox-triage-research','philippines-customer-support-knowledge-handoff-research'],['Which messages should escalate?','Messages involving sensitive data, commitments, complaints, legal issues, or unclear authority.']],
 ['philippines-travel-coordination-research','Philippines travel coordination: itinerary and approval controls','A research brief on itinerary support, identity checks, change evidence, and owner decisions for travel arrangements.','7 checks before an itinerary update is released','travel coordination','one itinerary segment for one traveler and one travel period','reservation, traveler, local time zone, and requested change','committing spend or making a material change without approval','missing identity detail or conflicting segment','Travel access should be limited to details required for coordination.','Current, cancelled, prior, and proposed segments should not be mixed.','The traveler or designated owner approves material changes.','the record shows what was requested, confirmed, and approved.',['philippines-calendar-management-research','philippines-document-management-research'],['What is an important date check?','Compare local departure and arrival dates with the source reservation and traveler time zone.']]
];
export const august13ResearchPosts:readonly ResearchPost[]=configs.map(c=>{const [slug,title,excerpt,stat,subject,unit,noun,result,boundary,exception,access,period,owner,conclusion,related]=c as any;return {slug,title,excerpt,published:'2026-08-13',thumbnail:'/research-thumbnails/research-batch-2026-08-10.svg',headlineStat:stat,body:[...body(subject,unit,[`The source should identify the ${noun}, requested result, date checked, and record from which each field came.`,`The specialist can prepare ${result}, but the client owner retains ${boundary}.`,`An incomplete, conflicting, or stale record is an ${exception}; route it with evidence rather than silently repairing it.`,`${access}`,`${period}`,`The owner should approve the release condition and exception path. ${owner}`,`The bounded conclusion is that ${conclusion}.`,...A(subject,noun,result,boundary,exception,access,period,owner,conclusion)])],methodology:'Methods note: comparative desk review of NIST Cybersecurity Framework 2.0, NIST Privacy Framework, FTC data-security guidance, ISO 9001, U.S. National Archives records guidance, and W3C WCAG 2.2. These sources establish control principles, not provider performance or a guarantee for a client.',sources,related,faq:[{question:'What should a reviewer preserve?',answer:'The source reference, period, sample, exception note, and accountable owner decision.'},{question:'What is the boundary?',answer:'Routine preparation can be delegated; material judgments and exceptions remain with the authorized owner.'}]};});
