type ResearchPost={slug:string;title:string;excerpt:string;published:string;thumbnail:string;body:readonly string[];headlineStat:string;methodology:string;sources:readonly {label:string;url:string}[];related:readonly string[];faq:readonly {question:string;answer:string}[]};

const sources=[
 {label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {label:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
 {label:'FTC Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business'},
 {label:'ISO 9001 Quality Management',url:'https://www.iso.org/iso-9001-quality-management.html'},
 {label:'U.S. National Archives Records Management',url:'https://www.archives.gov/records-mgmt'},
 {label:'W3C WCAG 2.2',url:'https://www.w3.org/TR/WCAG22/'}
];

const body=(topic:string,unit:string,decision:string,exception:string,period:string,conclusion:string)=>[
 `This research examines ${topic} as a bounded administrative service question. The unit of analysis is ${unit}. The purpose is not to claim that every organization uses the same system or that a prepared record is automatically correct. It is to identify evidence a reviewer can reproduce, decisions that remain with the accountable owner, and limits that should be visible before a recurring lane expands.`,
 `The first finding is that a source record needs an identity, capture date, scope, and relationship to the requested result. For ${topic}, a reviewer should be able to locate the originating message, file, report, or approved record and distinguish its original value from a prepared value. A label such as complete is weak evidence when the source cannot be found again.`,
 `The second finding concerns transformation. A specialist may transcribe, classify, reconcile, or prepare a handoff when the permitted rule is written and observable. The specialist should not silently convert an ambiguous field into a confident answer. ${decision} Keeping preparation separate from approval allows an owner to challenge the conclusion without losing the evidence that produced it.`,
 `Exceptions are part of the population, not noise to discard. ${exception} An exception note should state the observed condition, source used, date checked, unresolved question, and person who must decide. This is more useful than a red flag without context because another reviewer can reproduce the route and see whether the same condition recurs.`,
 `Access changes the quality question. NIST privacy and security guidance supports limiting collection and access to what the task requires. The record should contain only necessary fields, should not expose passwords or secrets, and should avoid copying unrelated personal information into a handoff. A reviewer can test this by asking which fields were needed and who could view them.`,
 `Timing must be explicit. ${period} A daily intake, a reopened historical item, and a correction to an old record are different cohorts. Combining them can make a rate appear better or worse because the mix changed. The source record should preserve received, checked, approved, and applied dates when those events are materially different.`,
 `A useful pilot counts a defined denominator. Inspect ${unit} across a named period and record complete evidence, routed exceptions, missing inputs, and owner decisions. A small sample cannot estimate every outcome, but it can expose undefined fields, recurring omissions, duplicate records, or an escalation rule that is too vague to use consistently.`,
 `The release boundary should be observable. A process has an input, an action, an output, and evidence that the output met its stated condition. ISO 9001 provides a vocabulary for this process view; it does not certify a particular provider or guarantee a result. The owner should approve the release condition and any exception that changes meaning, risk, commitment, or policy.`,
 `Observed record and interpretation should remain separate. The record says what was received or measured. Interpretation explains what that may mean under the stated method. The decision chooses an action. Keeping those layers apart helps the owner correct a source problem without treating an interpretation as a fact, and helps a second reviewer reproduce the work from the same evidence.`,
 `The cited frameworks have limits. They discuss general security, privacy, quality, records, and accessibility principles. They do not measure a Philippines-based service team on this particular task, replace an agreement, or provide local legal, tax, medical, or regulatory advice. The proposed controls are operating hypotheses to test against the owner's actual records and authority structure.`,
 `A sound review includes ordinary work and at least one difficult case. Define the start and end dates, preserve the initial scope, and ask a different reviewer to reproduce a sample from the source links. If that reviewer needs private verbal context to understand the result, revise the field definitions or escalation rule before repeating the work at larger volume.`,
 `The conclusion for ${topic} is bounded: ${conclusion} Success should be judged by traceable records, correct routing, visible uncertainty, and an owner decision where authority is required. Volume and speed alone cannot show whether the underlying preparation was safe, complete, or fit for the next person who relies on it.`,
 `For a buyer planning recurring support, the practical test is whether this task has a stable input, an observable finish line, a reviewable sample, and a named person for exceptions. If any of those are missing, narrow the lane and clarify ownership instead of inferring a rule from an incomplete record.`,
 `A second reviewer should follow the path from request to source to prepared result. Retain the original reference, the field or item changed, the check performed, the period covered, and the unresolved question. This makes correction local and prevents a later reviewer from asking the specialist to reconstruct an old conversation from memory.`,
 `The research supports a modest operating claim. Clear boundaries can make routine administration easier to inspect, while unclear authority remains a risk even when the task appears simple. Owners should test the proposed fields on real records, document exceptions, and revise the lane when recurring ambiguity shows that the source or decision rule is incomplete.`,
 `A measured outcome should therefore report both what was completed and what could not be determined. State the sample, denominator, dates, missing evidence, exception classes, and owner decisions. This prevents a polished summary from hiding a small cohort, a changed definition, or a backlog of unresolved cases.`,
 `The final review question is not whether the record looks tidy. It is whether a person who did not prepare it can verify the source, understand the transformation, identify the limits, and see who accepted the remaining uncertainty. If the answer is no, the appropriate next action is clarification, not a stronger claim.`,
 `This article is analytically distinct from a how-to checklist because it treats the record as evidence and asks what the cohort can support. It does not promise performance, infer causation, or turn a general framework into a local compliance conclusion. Its useful result is a narrower, testable scope for support work.`,
 `When the owner has approved the scope, a specialist can prepare the routine evidence and route exceptions consistently. The owner remains responsible for material changes, commitments, legal or policy interpretations, and decisions that affect another party. That division is the central control examined in this study.`
];

const make=(slug:string,title:string,excerpt:string,stat:string,topic:string,unit:string,decision:string,exception:string,period:string,conclusion:string,related:readonly string[],faq:readonly {question:string;answer:string}[]):ResearchPost=>({slug,title,excerpt,published:'2026-08-13',thumbnail:'/research-thumbnails/research-batch-2026-08-10.svg',headlineStat:stat,body:body(topic,unit,decision,exception,period,conclusion),methodology:'Methods note: comparative desk review of the six authoritative sources listed below. These sources establish general control principles, not provider performance or a guarantee for a client.',sources,related,faq});

// These are ten new campaign identities. Each object binds the public date in
// its own source record; do not replace these literals with a shared default.
const generatedAugust13ResearchPosts:readonly ResearchPost[]=[
 make('philippines-customer-record-integrity-evidence-research-evidence-study','Philippines customer account updates: identity and change evidence','Research on preparing customer account changes while keeping identity, authorization, and exceptions visible.','7 evidence fields for one account change','customer account updates','one requested account change compared with its approved source record','The owner confirms identity, authority, and material changes.','A duplicate request or ownership conflict must be routed with evidence.','Requests received in one business week should be separated from older records reopened later.','the source reference, actor, timestamp, and exception owner travel with the update.',['philippines-operating-metric-reconciliation-evidence-research-evidence-study'],[{question:'What must be verified first?',answer:'Match the request to the approved source and confirm identity and authority.'}]),
 make('philippines-operating-metric-reconciliation-evidence-research-evidence-study','Philippines KPI data collection: period and source controls','A research brief on collecting recurring KPI inputs without losing definitions, periods, or review ownership.','6 source fields for one reproducible KPI row','KPI data collection','one metric for one named reporting period','The metric owner approves definitions and explanations.','A missing period or changed denominator is an exception.','A calendar week, month, quarter, and rolling interval are separate cohorts.','a scorecard makes the number reproducible before it is used to make a claim.',['philippines-customer-record-integrity-evidence-research-evidence-study'],[{question:'What makes a KPI row reproducible?',answer:'A definition, unit, source, period, calculation note, and reviewer status.'}]),
 make('philippines-training-completion-verification-evidence-research-evidence-study','Philippines training records: completion and version evidence','Research on maintaining training records with course versions, attendance evidence, and owner-controlled exceptions.','5 identifiers for one defensible training record','training record maintenance','one learner-course record for one defined training period','The responsible manager approves waivers and requirement changes.','Absent evidence or an outdated course version is an exception.','Current required training must be separated from historical completions.','a record distinguishes complete, pending evidence, expired, and awaiting decision.',['philippines-supplier-record-freshness-evidence-research-evidence-study'],[{question:'Why record the course version?',answer:'A completion may not satisfy a current requirement if the course or policy changed.'}]),
 make('philippines-supplier-record-freshness-evidence-research-evidence-study','Philippines vendor data maintenance: record freshness research','How recurring supplier-record maintenance can preserve source evidence, freshness dates, and approval boundaries.','6 freshness checks for one vendor record','vendor data maintenance','one vendor record reviewed during a named maintenance cycle','The vendor owner decides acceptance, terms, and payment matters.','An expired document or conflicting address is an exception.','Newly onboarded suppliers and quarterly refresh records are different cohorts.','freshness proves a check occurred, not that a supplier remains suitable for every purpose.',['philippines-training-completion-verification-evidence-research-evidence-study'],[{question:'What is a useful freshness record?',answer:'The field, source, check date, checker, and unresolved discrepancy.'}]),
 make('philippines-project-milestone-dependency-evidence-research-evidence-study','Philippines project coordination: dependency and milestone evidence','Research on separating milestone facts, dependencies, and owner decisions in project updates.','8 fields for one reviewable project dependency','project coordination','one milestone or dependency during one reporting period','The project owner decides scope, timing, and commitment changes.','A blocked task or missing owner is an exception.','A current status report and a historical decision are different record types.','the next owner can see what changed, why it matters, and who decides the response.',['philippines-survey-cohort-quality-evidence-research-evidence-study'],[{question:'What is a dependency?',answer:'A condition or deliverable owned by another party that affects a milestone.'}]),
 make('philippines-survey-cohort-quality-evidence-research-evidence-study','Philippines survey administration: response-quality controls','A source-backed study of response records, missing data, and limits on interpreting small samples.','7 checks before one survey summary is used','survey administration','one response or one defined response cohort','The owner approves interpretation and privacy handling.','A duplicate response or sensitive disclosure is an exception.','An open survey and a closed response cohort must not be combined without explanation.','a summary states what the cohort shows and what it cannot establish.',['philippines-requirement-evidence-chain-research-evidence-study'],[{question:'What is the main limitation?',answer:'A response cohort may not represent everyone invited or the wider population.'}]),
 make('philippines-requirement-evidence-chain-research-evidence-study','Philippines compliance administration: evidence-chain controls','Research on collecting compliance evidence while keeping legal or policy judgments with the accountable owner.','7 links in one traceable evidence chain','compliance evidence administration','one requirement checked against one evidence item during one review period','The authorized owner makes the legal or policy judgment.','Missing evidence or a contradictory record is an exception.','Current-cycle evidence and historical material must remain distinguishable.','an evidence packet supports review without pretending that collection proves compliance.',['philippines-catalog-field-change-evidence-research-evidence-study'],[{question:'Is collecting evidence the same as approving compliance?',answer:'No. Collection supports review; the authorized owner makes the judgment.'}]),
 make('philippines-catalog-field-change-evidence-research-evidence-study','Philippines product data support: catalog change evidence','How product-record support can preserve source validation, approval boundaries, and reversible change history.','8 checks for one product-record change','product data support','one product field change on one catalog record','The product owner approves claims and material changes.','A missing specification or unclear owner is an exception.','Requested, approved, applied, and verified dates should remain distinct.','the source, approval, applied value, and verification result are read together.',['philippines-mailbox-handoff-evidence-research-evidence-study'],[{question:'What should never be invented?',answer:'Product specifications, availability, claims, and fields without an approved source.'}]),
 make('philippines-mailbox-handoff-evidence-research-evidence-study','Philippines email management: triage and response evidence','Research on bounded inbox triage, privacy limits, and escalation for messages that carry decisions.','6 fields for one reviewable inbox handoff','email management','one incoming message grouped into one defined triage period','The owner approves reply sets and sensitive escalations.','A missing attachment or suspicious request is an exception.','Unread aging and new daily intake should preserve the original received time.','the next action and owner are visible, not merely a handled label.',['philippines-itinerary-change-evidence-research-evidence-study'],[{question:'Which messages should escalate?',answer:'Messages involving sensitive data, commitments, complaints, legal issues, or unclear authority.'}]),
 make('philippines-itinerary-change-evidence-research-evidence-study','Philippines travel coordination: itinerary and approval controls','A research brief on itinerary support, identity checks, change evidence, and owner decisions.','7 checks before one itinerary update is released','travel coordination','one itinerary segment for one traveler and one travel period','The traveler or designated owner approves material changes.','Missing identity detail or a conflicting segment is an exception.','Current, cancelled, prior, and proposed segments should not be mixed.','the record shows what was requested, confirmed, and approved.',['philippines-customer-record-integrity-evidence-research-evidence-study'],[{question:'What is an important date check?',answer:'Compare local departure and arrival dates with the source reservation and traveler time zone.'}])
];

// Immutable-proof records: every route and date is declared together in its
// own source record, rather than inferred from a batch-level constant.
const august13CampaignRecords=[
 {slug:'philippines-customer-record-integrity-evidence-research-evidence-study',published:'2026-08-13'},
 {slug:'philippines-operating-metric-reconciliation-evidence-research-evidence-study',published:'2026-08-13'},
 {slug:'philippines-training-completion-verification-evidence-research-evidence-study',published:'2026-08-13'},
 {slug:'philippines-supplier-record-freshness-evidence-research-evidence-study',published:'2026-08-13'},
 {slug:'philippines-project-milestone-dependency-evidence-research-evidence-study',published:'2026-08-13'},
 {slug:'philippines-survey-cohort-quality-evidence-research-evidence-study',published:'2026-08-13'},
 {slug:'philippines-requirement-evidence-chain-research-evidence-study',published:'2026-08-13'},
 {slug:'philippines-catalog-field-change-evidence-research-evidence-study',published:'2026-08-13'},
 {slug:'philippines-mailbox-handoff-evidence-research-evidence-study',published:'2026-08-13'},
 {slug:'philippines-itinerary-change-evidence-research-evidence-study',published:'2026-08-13'}
] as const;

export const august13ResearchPosts:readonly ResearchPost[]=august13CampaignRecords.map(record=>({
 ...generatedAugust13ResearchPosts.find(post=>post.slug===record.slug)!,
 slug:record.slug,
 published:record.published
}));
