type ResearchPost={slug:string;title:string;excerpt:string;published:string;thumbnail:string;body:readonly string[];headlineStat:string;methodology:string;sources:readonly {label:string;url:string}[];related:readonly string[];faq:readonly {question:string;answer:string}[]};

const sources={records:{label:'U.S. National Archives Records Management',url:'https://www.archives.gov/records-mgmt'},quality:{label:'ISO 9001 Quality Management',url:'https://www.iso.org/iso-9001-quality-management.html'},security:{label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},privacy:{label:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},accessibility:{label:'W3C Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'},ftc:{label:'FTC Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business'}} as const;
type Config={subject:string;unit:string;question:string;finding:string;boundary:string;exception:string;cohort:string;measure:string;limit:string;faq:string;answer:string;sources:readonly {label:string;url:string}[]};

const body=(c:Config):readonly string[]=>[
 `Research question: ${c.question} This study treats ${c.subject} as a bounded administrative service question. The unit of analysis is ${c.unit}; it is not a claim about every customer, provider, or business process.`,
 `The method is a comparative desk review of the public records, quality, security, privacy, and accessibility guidance listed in Sources. The sources supply principles and definitions. They do not measure OutsourcedService.com, a Philippines-based team, or any local operating result.`,
 `The central finding is that a recurring support lane becomes reviewable only when its source, transformation, and owner are visible. ${c.finding} A finished-looking field without provenance is weak evidence because a later reviewer cannot tell whether it was copied, reconciled, inferred, or approved.`,
 `The record should begin with identity: a stable reference, source location, relevant time, current state, and responsible owner. Similar labels are not enough. A duplicate or stale item can create a false impression of volume, timeliness, or completion if the identity rule is not explicit.`,
 `The service boundary matters as much as the data fields. The support lane may collect, compare, format, tag, and route evidence when the rule is observable. ${c.boundary} Keeping that decision with the accountable owner protects both the customer and the person preparing the record.`,
 `An exception is not a vague note that something is “unclear.” ${c.exception} The exception record should state what was observed, which source was checked, when it was checked, what remains unknown, and who must decide. This creates a useful handoff without pretending that ambiguity has been resolved.`,
 `Cohort design changes the interpretation. ${c.cohort} New work, reopened work, corrections, and items waiting on another party have different clocks and causes. Combining them into one rate can make a queue look better or worse without any underlying change.`,
 `Timing should preserve event meaning. Received, acknowledged, reviewed, approved, corrected, and completed are different events. A duration should name its start and end points, its time zone where relevant, and any pause rule. Precision in the wrong interval is still a misleading measure.`,
 `Evidence should remain close to the claim it supports. A source link, record identifier, version, or short comparison note lets another reviewer reproduce the finding. A long narrative can be useful context, but it should not replace the underlying reference or conceal a missing source.`,
 `Privacy narrows what belongs in the working record. Retain the minimum information needed for the defined task, limit access by role, and avoid creating a second unrestricted copy of a customer or employee file. The NIST Privacy Framework and FTC guidance are guardrails for review, not proof that a particular implementation is compliant.`,
 `Security is also an operating boundary. Least-privilege access, named accounts, controlled sharing, and a way to remove access are more meaningful than a broad promise that data is “secure.” The lane should flag an access problem rather than work around it by exporting more information.`,
 `Quality should be checked against an agreed criterion. ISO 9001 is useful here because it separates inputs, activities, outputs, and evidence, but citing it does not certify this service or guarantee a result. The owner still defines what is acceptable for the actual record and decision.`,
 `A practical review sample should include ordinary items and difficult items. Record the population, selection rule, sample size, reviewer, criterion version, and disagreements. ${c.measure} Counts should precede percentages so the denominator and exclusions remain visible.`,
 `Interpretation must stay within the evidence. A high completion rate may reflect easy cases, exclusions, or a loose definition of complete. A low rate may reflect more approvals or missing inputs. The desk review can support a narrow statement about the defined sample; it cannot establish causation, universal performance, or a future promise.`,
 `A useful handoff names the item, current state, source, next action, owner, due condition, and unresolved question. It should distinguish a fact from a recommendation and a recommendation from an approval. That separation reduces the chance that a routine update is mistaken for a business decision.`,
 `Corrections need history. Preserve enough of the prior value or source reference to explain the change, while avoiding unnecessary duplication of sensitive information. Record who prepared the correction, who approved it when required, and which event should count in reporting.`,
 `The research does not prove that any particular tool, staffing arrangement, or schedule is best. It also does not replace legal, financial, security, accessibility, or privacy advice. Its purpose is narrower: identify the evidence and decision boundaries a buyer should test before delegating a recurring support lane.`,
 `A safe pilot starts with one named queue, a limited field set, a clear stop condition, and a sample review. If two reviewers disagree about the same item, pause expansion and clarify the criterion or authority rule. Increasing volume before resolving the ambiguity only makes the defect harder to isolate.`,
 `Conclusion: ${c.limit} The durable test is whether an owner can inspect what happened, understand what remains uncertain, and make the decision that requires authority. A Philippines-based specialist can keep routine evidence moving when the lane is narrow, access is controlled, and exceptions have a real owner.`,
 `The resulting scorecard should name the population, date range, source coverage, exception counts, corrections, owner decisions, and omissions. Those limits are part of the finding. They make the next review more useful than an unexplained activity total.`
];

const make=(slug:string,title:string,excerpt:string,headlineStat:string,c:Config,related:readonly string[]=[]):ResearchPost=>({slug,title,excerpt,published:'2026-08-17',thumbnail:'/research-thumbnails/research-batch-2026-08-10.svg',body:body(c),headlineStat,methodology:'Methods note: comparative desk review of the named public sources. The sources establish general principles and do not measure a provider, guarantee an outcome, or replace owner judgment.',sources:c.sources,related,faq:[{question:c.faq,answer:c.answer}]});

const batch:readonly ResearchPost[]=[
 make('philippines-vendor-follow-up-evidence-research','Philippines vendor follow-up: response evidence research','A study of vendor follow-up records that separates a documented response from a promise, approval, or commercial decision.','7 fields for one vendor follow-up record',{subject:'vendor follow-up for recurring operations support',unit:'one follow-up request linked to one vendor record and one source communication',question:'What evidence shows that vendor follow-up is complete without implying a commitment?',finding:'A follow-up record should connect the request, vendor identity, contact channel, response time, quoted condition, and next owner action.',boundary:'The owner retains authority for supplier selection, commitments, disputes, and changes to commercial terms.',exception:'A missing supplier identity, conflicting response, changed bank detail, or unanswered material question must be escalated.',cohort:'New requests, reminders, vendor replies, and disputes should be reported separately.',measure:'Report requests with a current source response, requests awaiting a vendor, owner decisions, and reopened follow-ups.',limit:'vendor administration can make communication traceable, but it cannot prove supplier performance or authorize a commercial outcome.',faq:'Does a vendor reply equal a completed follow-up?',answer:'No. It is evidence of a response; completion also depends on the defined next action and owner decision.',sources:[sources.records,sources.security,sources.privacy,sources.quality]}),
 make('philippines-crm-duplicate-detection-research','Philippines CRM duplicate detection: identity evidence research','Research on duplicate customer records, match confidence, and correction authority in recurring CRM administration.','6 identifiers for one duplicate decision',{subject:'CRM duplicate detection and record identity',unit:'one suspected duplicate pair compared under a stated matching rule',question:'When is a suspected CRM duplicate strong enough to route for correction?',finding:'A duplicate decision needs stable identifiers, field-level comparison, source freshness, match confidence, and a record of what was not compared.',boundary:'The support lane can identify and document a suspected match; the record owner approves merges, deletions, and changes to customer identity.',exception:'A shared household identifier, conflicting legal name, privacy restriction, or uncertain source must stop automated consolidation.',cohort:'New records, suspected duplicates, confirmed duplicates, and false-positive reviews need separate denominators.',measure:'Count pairs screened, routed, confirmed, rejected, and corrected, with the comparison rule and source date.',limit:'matching evidence can support a review request, but it cannot prove that two people or accounts should be merged without owner authority.',faq:'Can similar names prove a duplicate?',answer:'No. Names are one signal; identity requires the approved field set, source context, and owner review.',sources:[sources.privacy,sources.security,sources.records,sources.quality]}),
 make('philippines-payroll-input-reconciliation-research','Philippines payroll input reconciliation: evidence boundaries','A bounded study of payroll input preparation that keeps source matching separate from compensation and employment decisions.','8 checks for one payroll input exception',{subject:'payroll input reconciliation for administrative support',unit:'one payroll input compared with one approved source for one defined pay period',question:'What can an administrative reconciliation prove before payroll approval?',finding:'The record can show whether defined inputs were compared with an approved source and whether a variance was routed.',boundary:'The authorized payroll or people owner retains decisions about pay, classification, deductions, leave interpretation, and corrections.',exception:'A missing approval, conflicting hours, sensitive change, or unexplained adjustment must be held for review.',cohort:'Regular inputs, corrections, late submissions, and one-time adjustments should never share one completion metric.',measure:'Report inputs matched, variances found, approvals pending, corrections made, and items excluded from the defined period.',limit:'input reconciliation does not prove entitlement, legal compliance, or correct pay; it only documents a defined comparison.',faq:'What is the safe handoff for payroll support?',answer:'Provide the source, comparison result, variance, period, and approval request; leave the pay decision to the authorized owner.',sources:[sources.privacy,sources.security,sources.records,sources.quality]}),
 make('philippines-web-accessibility-issue-research','Philippines website accessibility issue triage: evidence research','Research on triaging accessibility findings while separating observable barriers from conformance conclusions.','5 evidence fields for one accessibility finding',{subject:'website accessibility issue triage for recurring content and admin support',unit:'one observed interface or content issue tested against one named WCAG criterion or user need',question:'How should support teams document an accessibility issue without overstating conformance?',finding:'A useful finding records the page, user-visible behavior, test context, criterion or concern, and evidence captured at the time of review.',boundary:'The support lane can reproduce, describe, and route an issue; the product or accessibility owner decides remediation priority and conformance claims.',exception:'An issue that affects authentication, essential content, or an unclear success criterion needs specialist review.',cohort:'New findings, retests, regressions, and accepted limitations should be tracked separately.',measure:'Report findings by criterion, severity rule, reproduction status, retest result, and owner disposition.',limit:'a desk check can identify an observed barrier, but it cannot certify full accessibility or represent every user’s experience.',faq:'Does one passing test prove accessibility?',answer:'No. It is evidence for the tested condition only; broader accessibility requires a defined evaluation scope.',sources:[sources.accessibility,sources.records,sources.quality,sources.privacy]}),
 make('philippines-customer-feedback-coding-research','Philippines customer feedback coding: cohort and privacy research','A study of coding customer feedback so recurring themes remain tied to a defined sample, source, and privacy boundary.','6 controls for one feedback cohort',{subject:'customer feedback coding for support and operations reporting',unit:'one feedback response coded against one versioned codebook',question:'What makes a coded feedback theme interpretable rather than anecdotal?',finding:'A theme needs a defined population, sampling rule, codebook version, source excerpt or identifier, and a way to record uncertainty.',boundary:'A coding specialist may classify and summarize; the business owner interprets material decisions and must not treat a small sample as a universal customer view.',exception:'A response containing sensitive data, ambiguous meaning, multiple themes, or an unsupported inference must be restricted or escalated.',cohort:'Invited responses, unsolicited comments, complaints, and post-resolution feedback should remain distinct.',measure:'Report responses sampled, coded, ambiguous, redacted, and excluded, with counts by cohort and codebook version.',limit:'coded feedback describes the selected responses; it does not estimate all customers or establish why a behavior occurred.',faq:'What does a feedback percentage require?',answer:'It requires the cohort, denominator, selection method, codebook, period, and exclusions beside the percentage.',sources:[sources.privacy,sources.records,sources.quality,sources.accessibility]}),
 make('philippines-project-dependency-status-research','Philippines project dependency status: evidence-led reporting','Research on project status reporting that separates a dependency’s existence from its impact, owner, and decision.','7 fields for one project dependency',{subject:'project dependency status reporting for recurring operations support',unit:'one dependency linking one deliverable, prerequisite, owner, and review date',question:'What evidence makes a project dependency status report decision-ready?',finding:'A dependency record should identify the blocked or exposed item, prerequisite, source, owner, condition, date, and consequence if unchanged.',boundary:'Support can gather status and prepare the report; the project owner decides scope, priority, deadline, risk acceptance, and stakeholder commitments.',exception:'A dependency with no owner, conflicting dates, or an unverified impact must be shown as unresolved.',cohort:'Open dependencies, resolved dependencies, overdue reviews, and newly discovered risks should not be collapsed.',measure:'Count dependencies by state, owner wait, evidence freshness, overdue review, and decision requested.',limit:'a status record can describe known dependencies; it cannot predict delivery or prove that a risk will materialize.',faq:'Is an overdue dependency automatically a project failure?',answer:'No. It is a status condition that needs context, owner review, and a defined consequence.',sources:[sources.records,sources.quality,sources.security,sources.privacy]}),
 make('philippines-service-request-priority-research','Philippines service request priority: decision-boundary research','A source-backed study of priority fields that keeps urgency evidence separate from owner-approved service commitments.','6 fields for one priority review',{subject:'service-request priority classification for recurring support queues',unit:'one service request classified under one versioned priority rule',question:'Can a support specialist assign priority without making a business commitment?',finding:'Priority is more defensible when the request type, impact evidence, time condition, rule version, and owner override are visible.',boundary:'The support lane can apply an approved rule and flag uncertainty; an owner retains decisions about exceptions, capacity promises, and high-impact handling.',exception:'A vague impact claim, safety or privacy concern, conflicting priority signals, or missing requester identity must be escalated.',cohort:'New requests, reprioritized items, owner overrides, and emergency cases need separate reporting.',measure:'Report requests by applied rule, override, escalation, age, and unresolved evidence gap.',limit:'a priority label describes a decision under a rule; it does not prove urgency, customer value, or the eventual service outcome.',faq:'Does a high priority label promise faster service?',answer:'No. It records classification under a rule; any service commitment requires the accountable owner.',sources:[sources.quality,sources.privacy,sources.security,sources.records]}),
 make('philippines-document-retention-review-research','Philippines document retention review: evidence and boundary research','Research on document retention review that distinguishes finding a record from deciding how long it should be kept.','5 evidence fields for one retention review',{subject:'document retention review for recurring administrative support',unit:'one named document or record series reviewed against an approved retention instruction',question:'What can a support lane establish during a document retention review?',finding:'The review can establish the record identity, current location, version or date, applicable instruction, and owner decision status.',boundary:'Support may inventory, label, and route records; the accountable owner decides retention, legal holds, disposal, and exceptions.',exception:'A disputed owner, legal hold signal, sensitive category, or conflicting schedule must stop routine disposition.',cohort:'Active records, duplicates, superseded versions, holds, and records awaiting owner decision must remain distinct.',measure:'Report records inventoried, matched to an instruction, unresolved, on hold, and awaiting owner approval.',limit:'an inventory finding does not authorize deletion or prove that a retention instruction is legally sufficient.',faq:'Can a duplicate be deleted during routine review?',answer:'Only under an approved rule and owner authority; a support review should route the candidate rather than decide disposition.',sources:[sources.records,sources.privacy,sources.security,sources.quality]}),
 make('philippines-customer-escalation-reason-research','Philippines customer escalation reasons: evidence and privacy research','A study of escalation reason coding that keeps sensitive complaints and policy judgments with the responsible owner.','7 fields for one escalation record',{subject:'customer escalation reason coding in recurring support work',unit:'one escalated case coded against one reason taxonomy and source conversation',question:'What makes an escalation reason useful for improving a support queue?',finding:'The record should preserve the customer issue, trigger evidence, route, urgency rule, owner, and unresolved decision without copying unnecessary personal data.',boundary:'Support can classify and route; managers retain decisions about complaints, refunds, policy exceptions, safety, and sensitive disclosures.',exception:'A threat, privacy request, vulnerable-customer signal, legal concern, or unclear policy match must use the protected escalation path.',cohort:'First escalations, repeat escalations, reopened cases, and owner-rejected escalations should be separated.',measure:'Count escalations by reason, source completeness, owner response, reopened state, and redaction or access restriction.',limit:'escalation counts reveal routing patterns in the defined queue; they do not measure sentiment, fault, or customer harm by themselves.',faq:'Should the full customer message be copied into an escalation report?',answer:'Only when necessary and permitted; use the minimum evidence and link to the controlled source where possible.',sources:[sources.privacy,sources.security,sources.records,sources.quality]}),
 make('philippines-recurring-report-definition-research','Philippines recurring report definitions: metric evidence research','Research on recurring operational reports that tests whether a number remains comparable when source definitions and periods change.','8 fields for one reproducible metric',{subject:'recurring operational report definition and source control',unit:'one reported metric for one named period, population, formula, and source snapshot',question:'What evidence makes a recurring report number reproducible?',finding:'A metric needs a definition, numerator, denominator, period, source, transformation, owner, and known exclusions beside the result.',boundary:'A reporting specialist can extract and reconcile inputs; the metric owner approves definitions, target changes, interpretation, and decisions based on the report.',exception:'A changed source field, missing denominator, late data, definition conflict, or unexplained manual adjustment must be visible.',cohort:'Actuals, forecasts, restatements, and corrected periods should not be compared as if they were the same observation.',measure:'Report source freshness, records included, exclusions, corrections, definition version, and reviewer sign-off.',limit:'a reproducible number is not automatically a valid measure of performance or a causal explanation.',faq:'Why keep the metric definition with the number?',answer:'Because a stable-looking number can change meaning when its population, formula, period, or source changes.',sources:[sources.quality,sources.records,sources.security,sources.privacy]})
];

const campaignRecords=[
 {slug:'philippines-vendor-follow-up-evidence-research',published:'2026-08-17'},
 {slug:'philippines-crm-duplicate-detection-research',published:'2026-08-17'},
 {slug:'philippines-payroll-input-reconciliation-research',published:'2026-08-17'},
 {slug:'philippines-web-accessibility-issue-research',published:'2026-08-17'},
 {slug:'philippines-customer-feedback-coding-research',published:'2026-08-17'},
 {slug:'philippines-project-dependency-status-research',published:'2026-08-17'},
 {slug:'philippines-service-request-priority-research',published:'2026-08-17'},
 {slug:'philippines-document-retention-review-research',published:'2026-08-17'},
 {slug:'philippines-customer-escalation-reason-research',published:'2026-08-17'},
 {slug:'philippines-recurring-report-definition-research',published:'2026-08-17'}
] as const;
export const august17ResearchPosts:readonly ResearchPost[]=campaignRecords.map(record=>({...batch.find(post=>post.slug===record.slug)!,slug:record.slug,published:record.published}));
