export const site = {
  domain: 'OutsourcedService.com',
  slug: 'outsourcedservice',
  brand: 'Outsourced Service',
  primary: 'Filipino service teams',
  audience: 'buyers planning recurring back office, admin, reporting, and customer work',
  angle: 'service scope, handoff rules, safe access, and review ownership',
  style: 'Service operations desk',
  dark: '#17304a',
  color: '#4e63f5',
  accent: '#b9f227',
  heroImage: '/filipino-service-workflow.svg',
  serviceImage: '/filipino-service-workflow.svg',
  alt: 'Two specialists reviewing a service workflow board',
  badge: 'Philippines only',
} as const;

export const services = [
  {
    slug: 'operations-support',
    title: 'Operations support',
    desc: 'Filipino operations support for recurring updates, handoffs, follow-up, and weekly checks, with the owner still in control.',
    bestFor: ['order updates', 'CRM cleanup', 'vendor follow-up', 'SOP checks'],
    firstWeek: ['choose five recurring tasks', 'share examples of finished work', 'set a daily handoff note', 'review the first 20 outputs'],
    ownerControls: ['approval rules for refunds, spend, and customer promises', 'limited tool access at launch', 'one scorecard for speed, accuracy, and follow-up'],
  },
  {
    slug: 'customer-support',
    title: 'Customer support',
    desc: 'Filipino customer support for tickets, shared inboxes, and follow-up, backed by scripts and clear escalation rules.',
    bestFor: ['tier-one tickets', 'shared inbox replies', 'status updates', 'review requests'],
    firstWeek: ['load approved replies', 'tag common issues', 'start with low-risk tickets', 'review escalations each day'],
    ownerControls: ['no refunds or policy exceptions without approval', 'sensitive complaints go to a manager', 'review a ticket sample each day'],
  },
  {
    slug: 'admin-support',
    title: 'Admin support',
    desc: 'Filipino admin support for calendars, documents, inbox work, data entry, and the follow-up that keeps slipping.',
    bestFor: ['calendar cleanup', 'document formatting', 'data entry', 'meeting follow-up'],
    firstWeek: ['make a daily admin list', 'share examples and templates', 'limit account permissions', 'check work before expanding the role'],
    ownerControls: ['approval before sensitive messages are sent', 'password-manager access by role', 'a daily list of done, blocked, and needs-review work'],
  },
  {
    slug: 'reporting-and-qa',
    title: 'Reporting and QA',
    desc: 'Filipino reporting and QA support for weekly numbers, sample checks, and issue logs that someone actually owns.',
    bestFor: ['weekly scorecards', 'ticket audits', 'SOP checks', 'simple KPI reports'],
    firstWeek: ['choose the numbers that matter', 'build a sample report', 'check a recent work sample', 'log issues with examples'],
    ownerControls: ['source links for every reported number', 'sample-size notes on audits', 'a short owner decision list'],
  },
] as const;

export const blogPosts = [
  {
    slug: 'philippines-knowledge-base-maintenance-control-guide',
    title: 'Philippines knowledge base maintenance: an update and approval control guide',
    excerpt: 'Plan a Philippines knowledge base maintenance lane with source checks, article owners, approval limits, safe access, and review evidence.',
    minutes: 12,
  },
  {
    slug: 'philippines-appointment-scheduling-control-guide',
    title: 'Philippines appointment scheduling: a calendar control and confirmation guide',
    excerpt: 'Plan a Philippines appointment scheduling lane with calendar rules, confirmation checks, safe access, and named owners for exceptions.',
    minutes: 12,
  },
  {
    slug: 'philippines-customer-onboarding-data-entry-control-guide',
    title: 'Philippines customer onboarding data entry: a control and review guide',
    excerpt: 'Build a Philippines customer onboarding data lane with source checks, field rules, safe access, review samples, and clear exception owners.',
    minutes: 12,
  },
  {
    slug: 'outsourced-order-processing-philippines-control-guide',
    title: 'Outsourced order processing Philippines: a control and exception guide',
    excerpt: 'Plan a Philippines order processing lane with clear checks, exception rules, safe access, and records the buyer can review.',
    minutes: 12,
  },
  {
    slug: 'customer-service-outsourcing-philippines-queue-escalation-guide',
    title: 'Customer service outsourcing Philippines: a queue and escalation guide',
    excerpt: 'Build a Philippines customer support queue with clear reply limits, escalation rules, access controls, and review evidence.',
    minutes: 12,
  },
  {
    slug: 'staff-outsourcing-philippines-direct-hire-or-staffing-provider',
    title: 'Staff outsourcing Philippines: direct hire or staffing provider?',
    excerpt: 'Compare direct hiring with a Philippines staffing provider by looking at recruiting work, daily management, access, quality checks, and exit duties.',
    minutes: 12,
  },
  {
    slug: 'outsourced-accounting-services-philippines-control-guide',
    title: 'Outsourced accounting services Philippines: a buyer control guide',
    excerpt: 'Plan a Philippines accounting support role with clear work limits, client-held approvals, careful access, and review evidence.',
    minutes: 13,
  },
  {
    slug: 'outsourced-service-tasks-to-outsource',
    title: 'How to outsource work to the Philippines: a 30-day plan',
    excerpt: 'Choose the right work, set safe access rules, and launch a Filipino service role without handing over owner-only decisions.',
    minutes: 12,
  },] as const;

export const generatedBlogPosts = [
  ['philippines-inbox-management-workflow', 'Philippines inbox management: a workflow and review guide', 'Build a safer inbox lane with triage rules, approved replies, escalation ownership, and a simple daily review.', 10],
  ['philippines-crm-data-cleanup-control-guide', 'Philippines CRM data cleanup: a control and handoff guide', 'Plan a CRM cleanup queue with source checks, field rules, duplicate handling, access limits, and review evidence.', 10],
  ['philippines-lead-follow-up-process-guide', 'Philippines lead follow-up: a process and escalation guide', 'Set up lead follow-up with approved messages, timing rules, source notes, and clear owner decisions.', 10],
  ['philippines-invoice-processing-control-guide', 'Philippines invoice processing: a control and approval guide', 'Design an invoice support lane that checks records, flags exceptions, and keeps payment approval with the owner.', 11],
  ['philippines-vendor-management-workflow-guide', 'Philippines vendor management: a workflow and records guide', 'Create a vendor update lane with document checks, renewal reminders, access controls, and escalation rules.', 10],
  ['philippines-calendar-management-control-guide', 'Philippines calendar management: a scheduling control guide', 'Hand off routine calendar work with time-zone rules, confirmation checks, and owner approval boundaries.', 10],
  ['philippines-document-processing-workflow-guide', 'Philippines document processing: a workflow and QA guide', 'Build a document queue with naming rules, source checks, version control, and sample-based quality review.', 10],
  ['philippines-market-research-support-guide', 'Philippines market research support: a source and review guide', 'Plan research support with source quality rules, evidence notes, synthesis limits, and a clear reviewer role.', 11],
  ['philippines-social-media-production-workflow', 'Philippines social media production: a workflow and approval guide', 'Organize content production with approved themes, asset checks, review gates, and owner-controlled publishing.', 10],
  ['philippines-email-marketing-operations-guide', 'Philippines email marketing operations: a control guide', 'Set up campaign operations with list checks, draft review, link testing, and permission boundaries.', 10],
  ['philippines-ecommerce-catalog-management-guide', 'Philippines ecommerce catalog management: a QA guide', 'Manage product records with source-of-truth rules, image checks, change logs, and escalation paths.', 10],
  ['philippines-recruiting-coordinator-workflow-guide', 'Philippines recruiting coordinator support: a workflow guide', 'Design a recruiting coordination lane with scheduling, record hygiene, candidate privacy, and decision limits.', 10],
  ['philippines-property-management-admin-guide', 'Philippines property management admin: a workflow guide', 'Plan routine property administration with request tracking, vendor follow-up, records, and owner approvals.', 10],
  ['philippines-logistics-coordination-control-guide', 'Philippines logistics coordination: a handoff and exception guide', 'Build a logistics support queue with status checks, updates, exception flags, and documented handoffs.', 10],
  ['philippines-podcast-production-support-guide', 'Philippines podcast production support: a workflow guide', 'Coordinate episode research, assets, transcripts, and publishing checks with a reviewable production board.', 9],
  ['philippines-website-content-operations-guide', 'Philippines website content operations: a QA guide', 'Create a content operations lane with briefs, source checks, metadata review, and publishing approval.', 10],
  ['philippines-customer-feedback-analysis-guide', 'Philippines customer feedback analysis: a review guide', 'Turn feedback into a tagged review queue with evidence, themes, privacy limits, and owner decisions.', 10],
  ['philippines-bookkeeping-data-prep-guide', 'Philippines bookkeeping data preparation: a control guide', 'Prepare bookkeeping records with source matching, exception queues, restricted access, and accountant review.', 10],
  ['philippines-sop-documentation-workflow-guide', 'Philippines SOP documentation: a workflow and review guide', 'Capture repeatable work in usable SOPs with examples, change ownership, version checks, and approval gates.', 10],
  ['philippines-operations-dashboard-maintenance-guide', 'Philippines operations dashboard maintenance: a QA guide', 'Maintain an operations dashboard with named sources, freshness checks, issue notes, and owner-controlled interpretation.', 10],
  ['philippines-client-reporting-support-guide', 'Philippines client reporting support: a control guide', 'Prepare client reports from approved sources with calculation checks, evidence links, and an accountable reviewer.', 10],
] as const;

export const batchBlogPosts = [
  { slug: 'philippines-shared-inbox-triage-guide', title: 'Philippines shared inbox triage: a practical workflow guide', excerpt: 'Create a shared inbox lane with labels, approved drafts, response windows, and clear escalation ownership.', focus: 'shared inbox triage', output: 'a tagged message with an approved draft or escalation note', risk: 'sensitive complaints, refunds, and promises outside the approved reply set' },
  { slug: 'philippines-crm-duplicate-record-review-guide', title: 'Philippines CRM duplicate review: a cleanup and control guide', excerpt: 'Reduce duplicate CRM records with match rules, source checks, merge limits, and review evidence.', focus: 'CRM duplicate review', output: 'a checked record list with merge recommendations and source links', risk: 'merging records when ownership, consent, or the source of truth is unclear' },
  { slug: 'philippines-sales-pipeline-hygiene-guide', title: 'Philippines sales pipeline hygiene: a review and handoff guide', excerpt: 'Keep sales stages useful with activity checks, stale-record queues, owner follow-up, and approval boundaries.', focus: 'sales pipeline hygiene', output: 'an updated opportunity record with an evidence note and next action', risk: 'changing forecasts, deal stages, or customer commitments without owner review' },
  { slug: 'philippines-purchase-order-admin-guide', title: 'Philippines purchase order administration: a control guide', excerpt: 'Build a purchase order support lane with document checks, status updates, and owner-controlled approvals.', focus: 'purchase order administration', output: 'a matched purchase order packet with an exception flag when needed', risk: 'approving spend, changing quantities, or accepting an invoice without authorization' },
  { slug: 'philippines-expense-receipt-review-guide', title: 'Philippines expense receipt review: a preparation and QA guide', excerpt: 'Prepare expense records with receipt matching, missing-item flags, restricted access, and accountant review.', focus: 'expense receipt review', output: 'a source-matched expense row with a clear missing-document note', risk: 'classifying disputed expenses or approving reimbursement' },
  { slug: 'philippines-customer-renewal-reminder-guide', title: 'Philippines customer renewal reminders: a workflow and escalation guide', excerpt: 'Manage renewal reminders with date checks, approved messages, record notes, and owner decisions for exceptions.', focus: 'customer renewal reminders', output: 'a dated reminder task with the approved message and account context', risk: 'negotiating terms, changing renewal dates, or making retention promises' },
  { slug: 'philippines-support-ticket-tagging-guide', title: 'Philippines support ticket tagging: a queue and QA guide', excerpt: 'Improve support reporting with consistent tags, evidence notes, priority rules, and a named escalation path.', focus: 'support ticket tagging', output: 'a correctly tagged ticket with a concise handoff note', risk: 'closing safety, privacy, legal, or high-impact complaints without review' },
  { slug: 'philippines-help-center-content-audit-guide', title: 'Philippines help center content audits: a source and approval guide', excerpt: 'Audit help center pages for stale claims, broken steps, source evidence, and controlled update approvals.', focus: 'help center content audits', output: 'an audit row showing the page, issue, source, and recommended action', risk: 'publishing a policy or product change before the responsible owner approves it' },
  { slug: 'philippines-customer-survey-coding-guide', title: 'Philippines customer survey coding: a review and privacy guide', excerpt: 'Turn survey responses into a consistent coding queue with privacy limits, evidence, and owner interpretation.', focus: 'customer survey coding', output: 'a coded response with the supporting excerpt and uncertainty flag', risk: 'revealing personal information or treating a small sample as a final business conclusion' },
  { slug: 'philippines-order-status-follow-up-guide', title: 'Philippines order status follow-up: a customer update guide', excerpt: 'Handle routine order updates with source checks, approved language, exception flags, and visible handoffs.', focus: 'order status follow-up', output: 'a source-checked status message and updated order note', risk: 'promising a delivery date, issuing credit, or overriding a fulfillment rule' },
  { slug: 'philippines-service-request-intake-guide', title: 'Philippines service request intake: a routing and control guide', excerpt: 'Make service request intake consistent with required fields, routing rules, priority checks, and escalation ownership.', focus: 'service request intake', output: 'a complete request record routed to the right work queue', risk: 'accepting scope, urgency, or commitments that require a manager decision' },
  { slug: 'philippines-meeting-notes-follow-up-guide', title: 'Philippines meeting notes and follow-up: a workflow guide', excerpt: 'Turn approved meeting notes into assigned follow-up with source context, due dates, and owner review.', focus: 'meeting notes and follow-up', output: 'a concise action list linked to the approved meeting record', risk: 'recording a decision, commitment, or sensitive statement that was not confirmed' },
  { slug: 'philippines-digital-file-organization-guide', title: 'Philippines digital file organization: a naming and access guide', excerpt: 'Organize shared files with naming rules, version checks, access limits, and a recoverable review trail.', focus: 'digital file organization', output: 'a correctly named file placed in the approved folder with its version note', risk: 'deleting records, changing retention settings, or moving restricted files' },
  { slug: 'philippines-contract-renewal-tracking-guide', title: 'Philippines contract renewal tracking: a control and reminder guide', excerpt: 'Track renewal dates with document checks, reminder ownership, evidence links, and clear legal escalation rules.', focus: 'contract renewal tracking', output: 'a renewal record with the source document, date, and next owner action', risk: 'interpreting legal language, accepting terms, or extending a contract' },
  { slug: 'philippines-website-quality-check-guide', title: 'Philippines website quality checks: a pre-publish workflow guide', excerpt: 'Run repeatable website checks for links, metadata, layout, and approval status before publishing.', focus: 'website quality checks', output: 'a QA checklist with tested URLs, findings, and approval state', risk: 'publishing unapproved claims, changing conversion routes, or editing production settings' },
  { slug: 'philippines-content-brief-production-guide', title: 'Philippines content brief production: a research and review guide', excerpt: 'Create usable content briefs with search intent, source notes, internal links, and an accountable reviewer.', focus: 'content brief production', output: 'a complete brief with audience, intent, outline, sources, and acceptance checks', risk: 'inventing facts, copying source text, or publishing without editorial approval' },
  { slug: 'philippines-competitor-research-support-guide', title: 'Philippines competitor research support: a source control guide', excerpt: 'Organize competitor research with dated sources, comparable fields, evidence notes, and limits on interpretation.', focus: 'competitor research support', output: 'a dated comparison row with the source and confidence note', risk: 'presenting an unverified claim as fact or making a strategic decision from a thin sample' },
  { slug: 'philippines-recruiting-interview-scheduling-guide', title: 'Philippines recruiting interview scheduling: a privacy and handoff guide', excerpt: 'Coordinate interviews with calendar checks, candidate privacy, confirmation steps, and decision limits.', focus: 'recruiting interview scheduling', output: 'a confirmed interview record with timezone, participants, and next step', risk: 'evaluating candidates, disclosing private data, or making a hiring decision' },
  { slug: 'philippines-training-record-maintenance-guide', title: 'Philippines training record maintenance: a review and access guide', excerpt: 'Maintain training records with completion checks, version control, access limits, and named owners for gaps.', focus: 'training record maintenance', output: 'an up-to-date training row linked to the approved course or evidence', risk: 'marking an incomplete requirement as finished or changing compliance status' },
  { slug: 'philippines-kpi-data-collection-guide', title: 'Philippines KPI data collection: a source and QA guide', excerpt: 'Collect recurring KPI inputs with source links, freshness checks, calculation notes, and reviewer ownership.', focus: 'KPI data collection', output: 'a source-linked metric row with period, definition, and check status', risk: 'changing metric definitions, interpreting performance, or altering targets' },
  { slug: 'philippines-customer-account-update-guide', title: 'Philippines customer account updates: a verification guide', excerpt: 'Process routine customer account updates with identity checks, source records, access limits, and escalation rules.', focus: 'customer account updates', output: 'a verified account change request with evidence and audit note', risk: 'changing payment, identity, legal, or security-sensitive fields without approval' },
  { slug: 'philippines-returns-case-administration-guide', title: 'Philippines returns case administration: a queue control guide', excerpt: 'Coordinate returns cases with status checks, document matching, approved messages, and owner decisions for exceptions.', focus: 'returns case administration', output: 'a complete return case with status, evidence, and next action', risk: 'approving refunds, waiving policy, or promising an exception to the customer' },
  { slug: 'philippines-work-order-coordination-guide', title: 'Philippines work order coordination: a status and exception guide', excerpt: 'Keep work orders moving with status updates, missing-detail checks, vendor follow-up, and controlled escalation.', focus: 'work order coordination', output: 'a current work order record with the next responsible party', risk: 'authorizing spend, changing scope, or closing work without completion evidence' },
  { slug: 'philippines-back-office-process-mapping-guide', date: '2026-08-10', title: 'Philippines back-office process mapping: a handoff guide', excerpt: 'Map recurring back-office work into clear inputs, outputs, review points, and escalation rules before assigning the queue.', focus: 'back-office process mapping', output: 'a documented process map with owners, inputs, outputs, and exception steps', risk: 'turning an undocumented judgment call into an automated or delegated task' },
  { slug: 'philippines-data-entry-quality-control-guide', date: '2026-08-10', title: 'Philippines data entry quality control: a source-check guide', excerpt: 'Improve data entry accuracy with source matching, required fields, sample checks, and a clear correction path.', focus: 'data entry quality control', output: 'a completed record checked against its source with any variance noted', risk: 'overwriting source data or assuming a missing value without approval' },
  { slug: 'philippines-accounts-receivable-follow-up-guide', date: '2026-08-10', title: 'Philippines accounts receivable follow-up: a control guide', excerpt: 'Organize routine receivables follow-up with aging checks, approved language, evidence notes, and owner-controlled decisions.', focus: 'accounts receivable follow-up', output: 'a dated follow-up record linked to the account and approved message', risk: 'negotiating payment terms, waiving balances, or making collection threats' },
  { slug: 'philippines-appointment-confirmation-workflow-guide', date: '2026-08-10', title: 'Philippines appointment confirmation: a workflow guide', excerpt: 'Run appointment confirmations with calendar checks, approved reminders, timezone clarity, and exception ownership.', focus: 'appointment confirmation', output: 'a confirmed appointment record with the message, time, and next step', risk: 'rescheduling outside policy or making clinical, legal, or service guarantees' },
  { slug: 'philippines-virtual-assistant-daily-queue-guide', date: '2026-08-10', title: 'Philippines virtual assistant daily queues: an operating guide', excerpt: 'Turn a broad virtual assistant role into a daily queue with priorities, finish lines, review samples, and safe access.', focus: 'virtual assistant daily queues', output: 'a prioritized daily worklist with completed evidence and blocked items', risk: 'giving broad owner-level access instead of task-specific permissions' },
  { slug: 'philippines-email-inbox-cleanup-guide', date: '2026-08-10', title: 'Philippines email inbox cleanup: a safe workflow guide', excerpt: 'Reduce inbox backlog with sorting rules, draft controls, labels, follow-up records, and a recoverable review trail.', focus: 'email inbox cleanup', output: 'a sorted inbox with labeled next actions and approved drafts where needed', risk: 'deleting messages, sending sensitive replies, or committing the owner to a decision' },
  { slug: 'philippines-podcast-show-notes-production-guide', date: '2026-08-10', title: 'Philippines podcast show notes production: a QA guide', excerpt: 'Create consistent podcast show notes with source checks, timestamps, links, review ownership, and publishing controls.', focus: 'podcast show notes production', output: 'a reviewed show-notes draft with timestamps, links, and approval status', risk: 'adding unsupported claims or publishing an episode asset without approval' },
  { slug: 'philippines-product-listing-quality-check-guide', date: '2026-08-10', title: 'Philippines product listing quality checks: a catalog guide', excerpt: 'Check product listings for source accuracy, required fields, media, links, and approval status before release.', focus: 'product listing quality checks', output: 'a checked listing record with findings and a release recommendation', risk: 'changing prices, claims, inventory status, or regulated product language' },
  { slug: 'philippines-lead-qualification-admin-guide', date: '2026-08-10', title: 'Philippines lead qualification administration: a routing guide', excerpt: 'Support lead qualification with required fields, source notes, routing rules, and clear limits on sales judgment.', focus: 'lead qualification administration', output: 'a complete lead record routed with evidence and an explicit next action', risk: 'promising outcomes, changing qualification policy, or representing the seller in negotiations' },
  { slug: 'philippines-customer-data-audit-guide', date: '2026-08-10', title: 'Philippines customer data audits: a privacy-aware workflow', excerpt: 'Review customer records for completeness and consistency while limiting exposure and escalating privacy-sensitive findings.', focus: 'customer data audits', output: 'an audit log with record identifiers, findings, source evidence, and owner actions', risk: 'exporting unnecessary personal data or making changes without an approved correction rule' },
  { slug: 'philippines-knowledge-base-search-optimization-guide', date: '2026-08-10', title: 'Philippines knowledge base search optimization: a review guide', excerpt: 'Improve help-center findability with query reviews, article gaps, source checks, and controlled editorial updates.', focus: 'knowledge base search optimization', output: 'a search-gap report linked to approved article recommendations', risk: 'changing policy guidance or publishing a factual claim without source review' },
  { slug: 'philippines-marketplace-order-support-guide', date: '2026-08-10', title: 'Philippines marketplace order support: a queue guide', excerpt: 'Coordinate marketplace orders with status checks, customer updates, evidence links, and controlled exception handling.', focus: 'marketplace order support', output: 'an updated order case with source status, approved message, and next owner', risk: 'issuing refunds, accepting disputes, or changing marketplace policy decisions' },
  { slug: 'philippines-website-content-refresh-guide', date: '2026-08-10', title: 'Philippines website content refreshes: a QA workflow', excerpt: 'Refresh website content with dated briefs, source checks, internal links, metadata review, and owner approval.', focus: 'website content refreshes', output: 'a reviewed content change set with source notes and approval state', risk: 'publishing unapproved claims or changing production conversion paths' },
  { slug: 'philippines-sales-operations-reporting-guide', date: '2026-08-10', title: 'Philippines sales operations reporting: a source-control guide', excerpt: 'Prepare recurring sales reports with metric definitions, source links, freshness checks, and an accountable reviewer.', focus: 'sales operations reporting', output: 'a source-linked report with definitions, period, checks, and open questions', risk: 'changing targets, interpreting performance for leadership, or altering pipeline ownership' },
  { slug: 'philippines-hr-record-maintenance-guide', date: '2026-08-10', title: 'Philippines HR record maintenance: an access-control guide', excerpt: 'Maintain routine HR records with required-field checks, version control, restricted access, and escalation boundaries.', focus: 'HR record maintenance', output: 'an updated HR record with source evidence and a review note', risk: 'making employment decisions, changing compensation data, or exposing sensitive personnel information' },
  { slug: 'philippines-appointment-intake-guide', date: '2026-08-10', title: 'Philippines appointment intake: a routing and review guide', excerpt: 'Standardize appointment intake with required details, routing rules, confirmation steps, and owner escalation.', focus: 'appointment intake', output: 'a complete request routed to the correct calendar or review queue', risk: 'accepting exceptions, interpreting professional advice, or promising availability outside the rules' },
  { slug: 'philippines-inventory-record-reconciliation-guide', date: '2026-08-10', title: 'Philippines inventory record reconciliation: a control guide', excerpt: 'Reconcile inventory records with source counts, discrepancy notes, approval limits, and a repeatable review cadence.', focus: 'inventory record reconciliation', output: 'a matched inventory record with variance evidence and an owner decision request', risk: 'adjusting stock, writing off items, or changing purchasing decisions without approval' },
  { slug: 'philippines-project-status-reporting-guide', date: '2026-08-10', title: 'Philippines project status reporting: an evidence guide', excerpt: 'Prepare project status reports from approved sources with milestone checks, blockers, owners, and clear decision requests.', focus: 'project status reporting', output: 'a dated status summary with linked evidence, risks, and next owners', risk: 'changing scope, deadlines, budgets, or stakeholder commitments' },
  { slug: 'philippines-customer-onboarding-checklist-guide', date: '2026-08-10', title: 'Philippines customer onboarding checklists: a handoff guide', excerpt: 'Keep onboarding consistent with required fields, document checks, task ownership, and controlled escalation.', focus: 'customer onboarding checklists', output: 'a completed onboarding checklist with missing items and owner actions visible', risk: 'approving eligibility, changing contract terms, or exposing sensitive customer data' },
  { slug: 'philippines-document-review-administration-guide', date: '2026-08-10', title: 'Philippines document review administration: a workflow guide', excerpt: 'Coordinate document review with version checks, reviewer assignment, source links, and clear completion evidence.', focus: 'document review administration', output: 'a review tracker showing document version, reviewer, status, and open questions', risk: 'giving legal, financial, or policy approval based on administrative review alone' },
  { slug: 'philippines-service-level-monitoring-guide', date: '2026-08-10', title: 'Philippines service-level monitoring: a queue guide', excerpt: 'Monitor recurring service levels with timestamp checks, exception queues, source definitions, and owner review.', focus: 'service-level monitoring', output: 'a source-backed service-level report with late items and escalation owners', risk: 'changing the service definition or promising remedies without approval' },
  { slug: 'philippines-customer-review-moderation-guide', date: '2026-08-10', title: 'Philippines customer review moderation: a policy guide', excerpt: 'Support review moderation with policy matching, evidence capture, privacy limits, and escalation for ambiguous cases.', focus: 'customer review moderation', output: 'a moderation record with policy basis, evidence, and reviewer decision status', risk: 'removing content or responding publicly when policy application is unclear' },
  { slug: 'philippines-recurring-task-management-guide', date: '2026-08-10', title: 'Philippines recurring task management: an operating guide', excerpt: 'Build a dependable recurring task queue with due dates, completion evidence, exceptions, and weekly owner review.', focus: 'recurring task management', output: 'a current task board with completed evidence, overdue reasons, and next actions', risk: 'silently changing priorities or closing work without completion evidence' },
  { slug: 'philippines-call-answering-workflow-guide', date: '2026-08-10', title: 'Philippines call answering workflows: a routing guide', excerpt: 'Set up call answering support with approved scripts, caller notes, routing rules, and clear escalation ownership.', focus: 'call answering workflows', output: 'a complete call record with the approved note, route, and next action', risk: 'making commitments, giving advice, or handling sensitive calls without the owner queue' },
] as const;

export const stats = [
  { label: 'Role scope', value: 'Tasks first', note: 'define the repeated work before settling on a title' },
  { label: 'Access plan', value: 'Start narrow', note: 'open only the tools and permissions the role needs' },
  { label: 'Quality review', value: 'Check samples', note: 'read real work before adding more responsibility' },
] as const;

export const staffingOffer = {
  partner: 'a Philippines staffing partner',
  promise: 'Get a staffing plan for Filipino talent, built around the work you want handled.',
  fit: [
    'owners who want Filipino talent but do not want to screen alone',
    'teams that need backup coverage and a named management path',
    'companies planning admin, operations, customer support, calls, bookkeeping, development, or marketing work',
  ],
  included: [
    'a role-planning call that turns the task list into a usable scope',
    'Filipino talent matching based on skills, schedule, tools, and communication needs',
    'onboarding guidance for SOPs, scorecards, reporting, and safe tool access',
    'a management path for quality, attendance, and replacement questions',
  ],
  proof: [
    'a written task scope before hiring',
    'a weekly reporting rhythm',
    'a named escalation owner',
    'a handoff plan for tools, SOPs, and checks',
  ],
} as const;

export const leadQuestions = [
  'What work do you want off your plate first?',
  'Which tools, inboxes, phones, CRMs, or systems will the person use?',
  'What hours and response window do you need?',
  'Who checks quality during the first two weeks?',
  'What should never be decided without approval?',
] as const;

export const staffingProcess = [
  { step: '1', title: 'Map the queue', body: 'Turn the loose task list into one role with outcomes, tools, limits, and a first-week checklist.' },
  { step: '2', title: 'Match Filipino talent', body: 'A Philippines staffing partner can match the role to the right skills, schedule, and communication style.' },
  { step: '3', title: 'Open access slowly', body: 'Start with examples, limited permissions, daily review, and one simple scorecard.' },
  { step: '4', title: 'Add work after it settles', body: 'Once the first tasks are stable, expand the role without turning the handoff into a mess.' },
] as const;

export const staffingFitNote = 'Every request is limited to talent in the Philippines. Fit still depends on the work, schedule, tools, skill level, and management needs.';
