const image = '/filipino-service-workflow.svg' as const;

// Publication remains intentionally unset while these drafts are off production.
// The Blog integrator sets it to the actual UTC release date immediately before
// the sole combined push, then the live verifier confirms that same date.
export const october5BlogDrafts = [
  {
    slug: 'ticket-priority-drift-audit-philippines',
    title: 'How to Audit Ticket Priority Drift Without Rewriting Support Policy',
    image,
    minutes: 9,
    excerpt: 'A practical audit for checking whether support tickets still follow the approved priority rules, with evidence, calibration cases, and manager-owned exceptions.',
    sources: [
      'https://www.nist.gov/cyberframework',
      'https://www.gao.gov/products/gao-20-283g',
      'https://www.cisa.gov/resources-tools/resources/cisa-insights-cyber-escalation',
    ],
    body: [
      `A support queue can appear orderly while its meaning slowly changes. One agent marks every unhappy customer as urgent. Another reserves the highest priority for an outage. A third follows an old macro that uses a category the team retired months ago. The queue still has labels, but those labels no longer produce a dependable sequence of work. A ticket-priority drift audit gives a Philippines-based support specialist a bounded way to find that problem. The specialist tests classifications against the current rule and records exceptions; the support owner keeps authority to define priority, accept risk, and decide what customers are promised.`,
      `Priority drift is different from an ordinary ticket-quality review. A quality review asks whether an individual response was accurate, complete, and appropriate. A drift audit asks whether the decision rule is being applied consistently across time, channels, agents, and issue types. That distinction matters because a polished reply can still sit in the wrong lane. If a security concern, service outage, vulnerable customer, or contractual deadline receives a routine label, good writing will not repair the routing error. Conversely, routinely inflating low-impact requests can crowd genuinely urgent work out of view.`,
      `Start by naming one authoritative priority policy. Record its owner, version, effective date, and approved location. If email guidance, a help-desk field description, and a training slide disagree, the specialist should not choose whichever rule seems sensible. Log the conflict and send it to the policy owner. The audit can proceed only on cases where the effective rule is clear. This source discipline keeps the exercise from becoming an unofficial policy rewrite and makes later results reproducible. A reviewer should be able to open the cited version and reach the same interpretation.`,
      `Build the sample around risk, not convenience. A purely random sample may contain mostly easy routine tickets and miss the edges where drift matters. Use separate groups for the highest priority, the lowest priority, tickets reclassified after creation, tickets that breached a response target, and a small random set from the middle. Add channels or products only when they use the same approved rubric. Record the population, period, selection method, sample size, and exclusions. The figures are evidence about that sample, not a claim about every ticket the company has ever handled.`,
      `For each selected ticket, create a compact evidence row. Include the ticket identifier, creation time and timezone, original priority, current priority, issue type, channel, customer impact facts available at classification time, the rule clause used for the test, the auditor's proposed result, and a link to the native record. Preserve later facts separately. An outage discovered three hours after a ticket arrived must not be treated as information the first agent necessarily possessed. This time-aware view avoids unfairly scoring decisions with hindsight while still revealing whether the queue was updated when material facts changed.`,
      `Use three audit results rather than a forced pass-or-fail choice. “Aligned” means the recorded priority follows the cited rule on the evidence available. “Not aligned” means a different priority clearly follows from that rule. “Needs owner interpretation” means the rule is silent, contradictory, or dependent on a business judgment the auditor does not own. That third state is essential. Without it, a specialist is pushed to invent thresholds for reputational harm, safety, legal exposure, strategic accounts, or financial loss. Those judgments belong to the designated support or risk owner.`,
      `Calibration should happen before the full sample. Ask the owner and auditor to classify five to ten redacted cases independently, including a routine request, a true urgent case, an emotional but low-impact complaint, a case with missing facts, and a case whose impact grew later. Compare the reasoning, not just the selected label. If both people choose “high” for different reasons, the apparent agreement may disappear on the next case. Update examples only through the policy's change process, retain the old version, and restart the sample if the decision rule materially changes.`,
      `The audit output should show where drift enters the workflow. Compare initial classifications with later changes. Group mismatches by rule clause, intake channel, issue type, team, and time period, while avoiding rankings that shame individual agents. A cluster from one web form may point to missing intake fields. A cluster after a product launch may show that the rubric lacks a new failure mode. A cluster across every channel may indicate vague wording. The corrective action differs: improve intake, clarify an example, change a field, coach a team, or escalate a policy gap.`,
      `Do not turn the mismatch rate into a standalone performance target. If managers reward a low mismatch percentage, auditors may avoid ambiguous cases or copy the original priority. Report the denominator, the three result states, and the number of cases that could not be tested because evidence was missing. Pair the result with operational consequences such as urgent tickets found in routine queues, low-impact tickets occupying urgent capacity, and average time to correct a classification. Keep customer outcomes descriptive unless the team has an approved method for attributing them to priority.`,
      `Access should match the audit. The specialist needs read access to the selected tickets, the approved priority rule, and a controlled audit register. Editing priority fields is not required to discover drift and creates a risk that source evidence will be overwritten. Where sensitive tickets contain payment, health, legal, security, or identity information, use redacted views or a smaller authorized review group. Named accounts, multifactor authentication, and an access expiry date make the lane easier to govern. NIST's Cybersecurity Framework is a useful source for organizing access and governance discussions, while the company's own policy remains the classification authority.`,
      `A useful daily handoff is short and decision-ready: “Twenty-four cases tested; sixteen aligned, five not aligned, and three need interpretation. Four of the five mismatches came from the marketplace channel, where the intake form does not capture service impact. Two interpretation cases involve a new product dependency. No priority fields were changed. The owner needs to confirm the rule for that dependency before tomorrow's sample.” This tells a manager what was checked, what pattern matters, what stayed untouched, and which decision unblocks the work.`,
      `Consider a practical example. A software company defines urgent as a broad service interruption with no workaround. Its marketplace form offers only “problem” and “question,” so agents infer urgency from frustrated language. The auditor samples reclassified cases and discovers that several angry billing questions began as urgent, while two multi-user access failures began as routine because the customer used calm wording. The answer is not to tell the specialist to judge tone more cleverly. The owner adds an impact question to intake, supplies two approved examples, and asks the team to recheck tickets when affected-user counts change.`,
      `Finish the audit with an owner action register. Each action needs a problem statement, cited evidence, accountable owner, due date, and validation check. Keep policy changes separate from operational fixes. A new priority definition requires approval and communication; a missing form field may require a product change; inconsistent application may require coaching and a fresh sample. Close an action only when its check is complete, not when someone says the matter was discussed. Then schedule a limited follow-up sample so the team can see whether the correction changed real classifications.`,
      `This is a good outsourced support task because evidence collection, sampling, comparison, and exception logging are repeatable. It is a poor task to delegate without boundaries because priority can carry customer, contractual, security, and safety consequences. Scope the Philippines-based specialist around a current rule, a documented sample, and an explicit stop state. Keep rule ownership, sensitive escalation, disciplinary decisions, and customer commitments with the responsible manager. To shape this into a real role, review the ticket queue management service scope and bring a redacted week of ticket data to the OutsourcedService.com contact conversation.`,
    ],
  },
] as const;
