const published='2026-10-08' as const;
const image='/aug23-heroes/outsourced-operations-decision-register.png' as const;
const thumbnail='/aug19-heroes/service-delivery-source-quality-evidence-research.webp' as const;
const sources=[
  {label:'GAO Standards for Internal Control in the Federal Government',url:'https://www.gao.gov/greenbook'},
  {label:'NIST SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {label:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {label:'U.S. National Archives records management',url:'https://www.archives.gov/records-mgmt'}
] as const;

type BlogSpec={slug:string;title:string;excerpt:string;work:string;owner:string;decision:string};
const blogSpecs:BlogSpec[]=[
 {slug:'service-queue-duplicate-owner-assignment',title:'How to Resolve Duplicate Owners in a Service Queue',excerpt:'Preserve assignment events, clarify current responsibility, and keep customer work from disappearing between two apparent owners.',work:'a service case that shows two active owners',owner:'the queue manager and business process owner',decision:'which owner is accountable now and how the conflicting assignment should be corrected'},
 {slug:'customer-update-source-version-conflict',title:'How to Handle a Customer Update Source-Version Conflict',excerpt:'Compare the approved source, message draft, and later changes before sending a status that may already be stale.',work:'a customer update whose source record changed after drafting',owner:'the customer-communication and source-system owners',decision:'which source version supports the message and whether a new approval is required'},
 {slug:'outsourced-handoff-missing-acceptance-event',title:'How to Repair an Outsourced Handoff Missing Its Acceptance Event',excerpt:'Reconstruct what transferred, who received it, and what remained open without inventing acknowledgement after the fact.',work:'a handoff with evidence of sending but no attributable acceptance',owner:'the outgoing and incoming service owners',decision:'whether responsibility transferred and which open items require renewed acknowledgement'},
 {slug:'service-sla-clock-pause-evidence',title:'How to Document Evidence for an SLA Clock Pause',excerpt:'Separate active handling, approved waiting states, and unsupported pauses with a reproducible event chronology.',work:'a service-level clock that paused while the case remained open',owner:'the service policy and case owners',decision:'whether the pause follows the approved rule and which time belongs in performance reporting'},
 {slug:'customer-case-attachment-replacement-review',title:'How to Review a Replaced Customer Case Attachment',excerpt:'Retain both versions, compare material differences, and route meaning or authority changes to the right owner.',work:'a customer case whose attachment was replaced under the same visible name',owner:'the content, privacy, and case owners',decision:'which version governs the next action and whether earlier work must be repeated'},
 {slug:'operations-checklist-step-supersession',title:'How to Track a Superseded Operations Checklist Step',excerpt:'Make changed instructions visible without erasing the procedure and evidence that applied to earlier work.',work:'an operations checklist step changed during an active work batch',owner:'the procedure owner and work-queue manager',decision:'when the new step becomes effective and which in-flight items require rework'},
 {slug:'service-escalation-recipient-identity-check',title:'How to Check Recipient Identity Before a Service Escalation',excerpt:'Verify the authorized recipient, minimize sensitive context, and preserve the routing decision before escalating.',work:'a sensitive escalation addressed to an uncertain recipient identity',owner:'the service, privacy, and security owners',decision:'which verified recipient may receive the minimum necessary case information'},
 {slug:'weekly-report-metric-definition-drift',title:'How to Detect Metric-Definition Drift in a Weekly Service Report',excerpt:'Tie each number to its current definition, source, period, and exclusions before publishing a polished but misleading trend.',work:'a weekly metric whose calculation or denominator changed',owner:'the reporting and business metric owners',decision:'which definition applies and how the break in comparability should be disclosed'},
 {slug:'customer-macro-approval-expiry-review',title:'How to Review an Expired Customer Reply Macro Approval',excerpt:'Connect reply wording to its approval window, current policy source, and owner decision before reuse.',work:'a customer reply macro whose approval or policy basis has expired',owner:'the support policy and communication owners',decision:'whether the wording remains approved, needs revision, or must be withdrawn'},
 {slug:'shared-inbox-alias-routing-conflict',title:'How to Resolve a Shared-Inbox Alias Routing Conflict',excerpt:'Trace recipient, alias, rule, case, and owner events before redirecting messages or promising a response.',work:'a shared-inbox message routed by conflicting alias rules',owner:'the inbox administrator and business queue owner',decision:'which queue owns the message and how the routing rule should change'},
 {slug:'service-access-role-coverage-gap',title:'How to Handle a Service Access-Role Coverage Gap',excerpt:'Document blocked work and request the minimum authorized access without borrowing identities or broadening privileges.',work:'a recurring service task blocked because no active role has the needed permission',owner:'the system, security, and service owners',decision:'whether to provision, reassign, redesign, or stop the task'},
 {slug:'service-case-closure-reopen-trigger',title:'How to Define a Service Case Reopen Trigger',excerpt:'Distinguish new evidence, failed implementation, customer follow-up, and unrelated work so closure metrics remain honest.',work:'a closed case that receives a new event or customer message',owner:'the case process and reporting owners',decision:'whether to reopen the original case, create related work, or retain closure'}
];

const makeBlog=(s:BlogSpec)=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published,image,minutes:12,sources:sources.map(x=>x.url),body:[
 `A recurring service queue becomes unreliable when ${s.work} is handled through memory or private chat. Open one controlled case and record the company entity, customer or record identifier, queue, channel, dates, current status, and exact unresolved question. Preserve the source before refreshing, editing, forwarding, or correcting it. A screenshot can support review, but a stable native record, export, version, or event identifier is stronger. The first objective is not to make the case look clean. It is to preserve what the service specialist actually received and what the systems showed at that moment.`,
 `Write the authority boundary at intake. ${s.owner} must decide ${s.decision}. A Philippines-based service specialist may gather sources, normalize fields, prepare a chronology, draft a bounded update, and route the question. The specialist should not invent approval, change policy, remove a control hold, broaden access, reveal sensitive information, or promise an outcome. Naming the owner and decision early prevents administrative follow-up from silently turning into business authority.`,
 `Build a source register. For every document, message, system record, policy, checklist, approval, and report, record its location, owner, identifier, version, retrieval time, effective time, and permitted use. Keep original values beside normalized values. Similar titles, totals, customer names, or subject lines are comparison signals, not proof that two records describe the same obligation or event. Mark evidence received from an unverified person, an editable report, or a system view that does not retain history.`,
 `Protect data while making the packet reviewable. Keep account, identity, payment, personnel, health, contract, or security details in the approved system and expose only the minimum necessary fields in the working queue. Use stable references and masked tokens instead of copying secrets. If the case requires a recipient change or cross-customer comparison, stop and involve the privacy or security owner before sharing content. Evidence completeness never justifies uncontrolled duplication of sensitive records.`,
 `Reconstruct the chronology with original timestamps and timezones. Include creation, receipt, assignment, acknowledgement, change, approval, hold, send, implementation, failure, correction, and verification events. Add normalized UTC values for comparison without replacing what each system displayed. Identify the actor or automated process and resulting state. A current status cannot prove which evidence or instruction existed earlier. Preserve unsuccessful attempts and reversals because they explain why the latest state changed.`,
 `Create a field comparison that cites its source. Compare identifiers, parties, owner, scope, status, version, amount where relevant, dates, permissions, approval state, and next action. Classify each row as aligned, different, missing, superseded, not applicable, or requiring owner interpretation. Do not overwrite a source value to make the rows agree. A formatting variation may be normalized, but a different entity, recipient, authority, policy version, access role, customer promise, or controlled status needs the named owner.`,
 `Test the stop conditions before routine work continues. Stop when identity is uncertain, evidence points to different customers or entities, sensitive data would cross an unauthorized boundary, a policy or contract must be interpreted, access is excessive or absent, a required approval is missing, or implementation could create an irreversible customer or financial consequence. Record the stop reason, affected work, owner, evidence already checked, and next review time. “Blocked” without this detail is not a useful queue state.`,
 `Prepare one bounded handoff. Summarize what agrees, what conflicts, what remains unavailable, and the operational consequence. Ask ${s.owner}: ${s.decision}? Link the source register, event chronology, comparison table, and minimum necessary evidence. Include a response date, but never treat urgency as approval. A second reviewer should be able to reproduce the factual packet without private context, and the owner should be able to decide without repeating the whole investigation.`,
 `Use precise queue states such as source missing, identity unresolved, version conflict, approval pending, owner interpretation required, implementation pending, verification pending, or disposition recorded. If responsibility transfers, retain the old owner, new owner, transfer time, open question, attached evidence, and acknowledgement. Do not mark an item complete because it moved to another inbox. Ownership transfer is itself an event that needs evidence.`,
 `After an authorized decision, verify the implemented outcome against the right record. Capture the decision owner, time, reason, approved value or state, implementing actor, and system result. Check that a correction did not affect another case, customer, entity, version, message, or reporting period. A successful system status is not enough when the wrong target can also succeed. Preserve before-and-after evidence and append later corrections instead of rewriting history.`,
 `Close the case only when the original question has an attributable disposition and every residual item has an owner. Check related drafts, duplicate cases, stale messages, old permissions, reports, automations, and pending actions. Communicate externally only with approved wording and verified recipients. If the customer outcome cannot yet be confirmed, state what was verified and what remains pending rather than converting an internal action into a promise of resolution.`,
 `Measure process quality without rewarding unsafe speed. Useful measures include source completeness, time to named ownership, evidence-request cycles, reopen rate, classification agreement, implementation mismatches, and repeated causes. Do not rank staff by holds removed or cases closed. A controlled stop can be the correct outcome. Publish definitions, numerators, denominators, exclusions, and observation windows so leaders can distinguish a real process signal from a polished but unstable metric.`,
 `Test the procedure with an ordinary case, missing evidence, conflicting identity, urgent request, owner transfer, and a case that changes after approval. Give a backup reviewer only the retained packet and ask for the source, chronology, conflict, owner question, decision, and implemented result. Repair the checklist wherever undocumented knowledge was required. A process is not repeatable merely because its original specialist remembers what happened.`,
 `Finish with an owner action register. Each recurring defect needs a statement, evidence, accountable owner, target date, acceptance check, and result. System design, policy, training, access, and supplier or customer communication may require different owners. AP or service support can quantify the pattern and maintain the queue, but management owns control design and risk acceptance. That boundary turns ${s.work} into a durable operating workflow instead of an improvised exception.`
 ,`Publish the working rule with its field definitions, authoritative sources, approved channels, access limits, owner matrix, stop conditions, escalation timing, and representative examples. Keep the effective date and version so future reviewers know which rule governed each case. Revisit the rule after system migrations, policy changes, queue transfers, or repeated exceptions. The support team should record suggested improvements and affected evidence, while the accountable owner approves any change in authority, customer promise, risk treatment, or reporting definition. This final discipline makes the workflow trainable and auditable without pretending one resolved case eliminates the underlying control risk.`
]});
export const october8BlogPosts=blogSpecs.map(makeBlog);

type ResearchSpec={slug:string;title:string;excerpt:string;question:string;population:string;signals:string[]};
const researchSpecs:ResearchSpec[]=[
 {slug:'service-handoff-acceptance-latency-research',title:'Service handoff acceptance latency research',excerpt:'A time-aware study of sent, received, acknowledged, and owner-ready handoffs.',question:'how long service handoffs wait for attributable acceptance and which evidence gaps explain the delay',population:'routine, urgent, cross-team, and returned handoffs in recurring service queues',signals:['send event','recipient identity','receipt evidence','acceptance event','open obligations','first owner action']},
 {slug:'customer-update-source-lineage-research',title:'Customer update source-lineage research',excerpt:'A reproducible method for testing whether outbound updates trace to the source version and approval actually used.',question:'whether a customer-facing update can be reconstructed from the exact source and approval available when it was sent',population:'status emails, case replies, scheduled notices, and manager-approved customer updates',signals:['source version','draft version','approval event','send event','recipient scope','later correction']},
 {slug:'service-queue-owner-agreement-research',title:'Service queue owner-agreement research',excerpt:'A blinded-review study of whether independent reviewers identify the same current owner and escalation route.',question:'whether independent reviewers assign the same accountable owner and stop condition from the same frozen evidence',population:'cases spanning support, operations, reporting, content, administration, and exception queues',signals:['case identity','current owner','policy source','unresolved decision','stop condition','escalation route']},
 {slug:'shared-inbox-routing-recurrence-research',title:'Shared-inbox routing recurrence research',excerpt:'Research on repeated alias, rule, thread, and ownership failures after a routing case was closed.',question:'why shared-inbox routing exceptions recur after recorded closure',population:'reopened or repeated routing exceptions involving aliases, forwarding rules, threads, and queue ownership',signals:['original cause','closure basis','new trigger','recipient path','owner transfer','corrective action']},
 {slug:'service-access-removal-evidence-research',title:'Service access removal evidence research',excerpt:'A least-privilege protocol for accounts, sessions, tokens, automations, and saved artifacts at offboarding.',question:'whether service access and reusable artifacts are removed or reassigned at the authorized time',population:'departing employees, contractors, shared roles, service accounts, sessions, tokens, and saved automations',signals:['identity inventory','role removal','session revocation','token rotation','artifact ownership','post-removal test']}
];
const makeResearch=(s:ResearchSpec)=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published,thumbnail,headlineStat:`Six evidence signals: ${s.signals.join(', ')}`,methodology:`A bounded, reproducible study of ${s.population}. Sources checked October 8, 2026. It measures evidence and workflow state, not individual performance or legal validity.`,sources,related:[],serviceHandoff:{slug:'operations-support',label:'Philippines operations support service',lead:'Use this method to define a source-linked queue while your accountable owners retain policy and approval decisions in the'},faq:[{question:'What does this study measure?',answer:s.question+'.'},{question:'What remains with the owner?',answer:'Policy interpretation, sensitive exceptions, approvals, access authority, customer commitments, and risk acceptance.'},{question:'Can a support specialist close evidence gaps by inference?',answer:'No. Missing or conflicting evidence remains visible and is routed to the authorized owner.'}],body:[
 `This study asks ${s.question}. It examines ${s.population}. The purpose is to give service leaders a reproducible evidence model without shifting policy, customer commitments, security decisions, approval, or risk acceptance to an outsourced preparation role. The output is a population register, event chronology, independent review, and owner action packet. GAO's Green Book supplies the framework for responsibility, quality information, control activities, and monitoring. NIST SP 800-53 supports attributable audit events and least privilege. The NIST Privacy Framework and National Archives guidance support purposeful collection and durable records.`,
 `The population includes completed, held, rejected, transferred, corrected, superseded, and reopened items. Each row retains entity, stable case identifier, channel, relevant party, source versions, intake time, queue state, assigned owner, reviewer, decision event, implementation event, and final disposition. The six primary signals are ${s.signals.join(', ')}. Selection rules are frozen before outcomes are reviewed, and every exclusion receives a reason. Sensitive identity, customer, personnel, payment, and security data remains in approved systems and appears only as masked references in analytical files.`,
 `Time is evidence rather than decoration. Each event retains its original timestamp, timezone, actor or automated process, system, and stable event identifier. A normalized UTC value is added for comparison without replacing the original. Intake, packet-ready, route, acknowledgement, evidence request, response, decision, implementation, and verification are distinct events. This prevents waiting for missing source evidence from being attributed to an owner and prevents implementation delay from being attributed to a preparer. Clock conflicts remain limitations routed to the system owner.`,
 `Source preservation precedes analysis. Original messages, documents, exports, workflow histories, approval records, role assignments, and relevant correspondence receive stable identifiers or hashes where permitted. Extracted fields remain linked to their source and version. A current screen cannot prove what a reviewer saw earlier, and a replaced file cannot retroactively become the basis for a prior decision. Historical and later records remain connected by explicit change events. Evidence unavailable at the tested time is marked unavailable rather than inferred from the later outcome.`,
 `Reviewers apply an explicit taxonomy to ${s.signals.join(', ')}. Each field is aligned, different, missing, superseded, not applicable, or requires owner interpretation, with a source citation. Calculations show inputs, denominators, exclusions, precision, and result. Familiar names, matching totals, a successful status, or a prior case are not proof. Those observations can guide review but cannot resolve a difference in identity, authority, policy version, scope, recipient, access, or customer commitment.`,
 `Quality is tested with a blinded second review. Two reviewers receive the same frozen packet and independently record the six signals, missing evidence, current owner, stop condition, and bounded decision request. Agreement is measured separately for factual fields, classification, routing, and closure. Disagreements are adjudicated against sources and definitions rather than by choosing the faster answer. Original responses remain retained so a later taxonomy improvement does not erase evidence of the earlier ambiguity.`,
 `Challenge cases include two entities with similar names, a replaced attachment, timestamps near a cutoff, an approval followed by a source change, an automated state without an attributable actor, overlapping owners, a transferred queue, a sensitive recipient change, a rejected action later retried, and closure followed by new evidence. The method passes when reviewers reconstruct the same sources, chronology, factual differences, and accountable decision point. It fails when current state substitutes for historical evidence or when a support role resolves a controlled decision to improve a metric.`,
 `Role boundaries are integral. Service support may inventory sources, normalize timestamps, prepare comparisons, maintain an evidence queue, calculate declared measures, and route bounded questions. It may not interpret policy beyond written rules, approve customer exceptions, disclose sensitive data, grant privileged access, impersonate an owner, change contractual meaning, or promise an outcome. Business, support, privacy, security, reporting, system, and executive owners retain their assigned decisions. A missing owner is reported as a design defect rather than quietly absorbed by the analyst.`,
 `Measures include population completeness, source completeness, packet-ready rate, acknowledgement time, decision time, implementation time, evidence-request cycles, classification agreement, reopened items, repeated causes, and verified closure. Report distributions and denominators, not only averages. Stratify by cause, channel, service, owner role, risk, and workflow where samples permit. Do not rank individuals by raw speed or reward closure alone. A correct controlled stop can take longer and still be the better result.`,
 `Limitations include overwritten histories, inaccessible external systems, shared identities, clock drift, policy ambiguity, informal decisions, missing customer events, and small samples. The study cannot prove intent, fraud, legal validity, contractual authority, customer satisfaction, or causation from correlation. Its supported conclusion is narrower: ${s.question} can be examined when the population, source versions, chronology, roles, classifications, decision, implementation, and known limitations are preserved. Management owns any policy or system change prompted by the findings.`,
 `The final artifact contains the methods note, frozen population, data dictionary, source register, taxonomy, chronology, reviewer-agreement table, findings with denominators, challenge-case results, limitations, and action register. Each action names its accountable owner, required evidence, review date, and verification method. A compact case summary shows ${s.signals.join(', ')} and links each to original records. Corrections append a version instead of rewriting history. This gives leaders decision-grade evidence while keeping the outsourced role focused on preparation rather than approval.`
 ,`A pilot should cover at least one ordinary path, one missing-source path, one identity or ownership conflict, one urgent item, and one event that changes after an apparent decision. The team freezes those packets and asks an independent reviewer to reconstruct the same six signals, current state, and owner question. Any dependence on private chat, personal memory, or an undocumented screen becomes a documented evidence gap. The owner then decides whether to change the source system, procedure, access model, or review cadence. The pilot is a workflow test rather than proof that every future case will behave the same way.`
 ,`Reporting separates observations, interpretations, recommendations, and owner decisions. Observations cite records; interpretations state their assumptions; recommendations name the mechanism they intend to change; decisions identify the authorized person and effective time. Negative findings also identify the test performed, because “no issue found” without a method is not evidence. Retain superseded analyses when definitions change and recalculate only where the revised method permits comparison. This structure lets leaders understand uncertainty, compare periods honestly, and commission deeper work without turning a support analyst's plausible narrative into an unsupported operational fact.`
 ,`Retain the observation window, extraction time, code or query version, and responsible reviewer with every published table. Those details allow a later analyst to reproduce the count and explain why a corrected source or expanded population changes it.`
]});
export const october8Research=researchSpecs.map(makeResearch);
