const published='2026-09-11' as const;
const image='/filipino-service-workflow.svg' as const;
const blogTopics=[
['vendor-master-record-change-intake','Control Vendor Master Record Change Intake Without Approving Payments','vendor master record changes','vendor, certificate type, source file, expiry date, request state, and risk owner','coverage limits, exclusions, or whether a certificate is acceptable','expired files, incorrect dates, unanswered requests, and unresolved owner decisions'],
['customer-refund-evidence-packet','Prepare Customer Refund Evidence Packets Without Authorizing Refunds','customer refund evidence packets','matter ID, received date, sender, original filename, source location, and assigned counsel','relevance, privilege, legal deadlines, or document meaning','misfiled originals, broken links, unclear matter IDs, and questions awaiting counsel'],
['multi-location-inventory-exception-log','Maintain a Multi-Location Inventory Exception Log Without Adjusting Stock','inventory exceptions across locations','supplier, item code, version, effective date, prior version, and technical reviewer','allergen, safety, labeling, regulatory, or acceptance questions','missed changes, wrong versions, absent source files, and late technical reviews'],
['contract-renewal-obligation-calendar','Build a Contract Renewal Obligation Calendar Without Interpreting Terms','contract renewal obligations','property, work-order ID, required evidence, vendor update, tenant notice, and manager','safety, workmanship, cost disputes, scope changes, or tenant complaints','unsupported closures, missing photos, reopened orders, and overdue manager checks'],
['product-return-inspection-intake','Organize Product Return Inspection Intake Without Deciding Disposition','product return inspection intake','study, site, expected document, version or date, approved location, and study owner','consent, eligibility, safety, protocol interpretation, or regulatory classification','false missing flags, wrong versions, misplaced records, and access blocks'],
['service-level-credit-request-register','Track Service-Level Credit Requests Without Granting Credits','service-level credit requests','supplier, service account, location, billing period, invoiced amount, and mapping source','coding, accruals, tax treatment, posting dates, or payment approval','stale mappings, transposed amounts, possible duplicates, and finance corrections'],
['employee-equipment-return-tracker','Run an Employee Equipment Return Tracker Without Making HR Decisions','employee equipment returns','object ID, agreement, condition-report state, transport record, return date, and registrar','object condition, handling requirements, contract meaning, or permission to transport','missing reports, conflicting dates, restricted images, and registrar decisions'],
['quality-corrective-action-evidence-log','Maintain a Quality Corrective Action Evidence Log Without Closing Findings','corrective action evidence','carrier circuit ID, site, service label, billing account, contract, and operational owner','whether a circuit is unused, should be disconnected, or should accept new terms','unmatched bills, unknown sites, conflicting identifiers, and missing contracts'],
['partner-onboarding-document-readiness','Check Partner Onboarding Document Readiness Without Approving the Partner','partner onboarding documents','requester, account, current entitlement, requested state, approval, and effective date','discounts, credits, contract changes, unusual access, or disputed requests','failed changes, missing approvals, state mismatches, and customer notices still due'],
['warranty-claim-status-reconciliation','Reconcile Warranty Claim Status Without Determining Coverage','warranty claim status','received timestamp, original request text, approved identifier, coordinator, source, and official status','disclosure, exemptions, legal deadlines, fees, or redactions','timestamp errors, changed request text, missing owners, and decisions without evidence'],
['regulated-training-record-reminder-queue','Operate a Regulated Training Record Reminder Queue Without Certifying Compliance','training record reminders','aircraft or component ID, record type, event date, revision, source, and issuer as shown','airworthiness, release to service, technical applicability, or regulatory meaning','wrong associations, unreadable files, identifier conflicts, and maintenance corrections'],
['facilities-access-deactivation-handoff','Coordinate Facilities Access Deactivation Without Making Security Decisions','facilities access deactivation','location, workstream, evidence requirement, due date, dependency, and accountable owner','permits, safety, employment, spending, brand exceptions, or the final opening decision','unsupported completions, hidden dependencies, late evidence, and owner decisions still open']
] as const;
export const september11BlogPosts=blogTopics.map(([slug,title,focus,fields,boundary,review],index)=>({slug,title,published,image,minutes:8+(index%3),excerpt:`A Philippines-based support routine for ${focus}, with source evidence and decisions kept with accountable owners.`,body:[
`${title} starts with a narrow administrative question: is the expected record present, identifiable, current, and routed to the right person? The specialist prepares evidence. An authorized owner makes any consequential decision.`,
`Use one approved register containing ${fields}. Copy source values as written and link the native record. If two sources disagree, preserve both values and mark the conflict instead of quietly choosing one.`,
`The specialist must escalate ${boundary}. Missing permission is also an exception. It is not permission to download sensitive material, use a personal account, or move records into an open folder.`,
`Keep ready, missing evidence, source conflict, and owner review as separate states. Administrative completeness must not look like technical, financial, legal, clinical, safety, or policy approval.`,
`Check a recurring sample against the original records. Count ${review} separately so the manager can see whether the routine, access model, upstream source, or approval path needs repair.`,
`The handoff lists completed records, blocked items, the exact question on each exception, and its next owner. That is the finish line for the support lane; approval remains outside it.`]}));
const sources=[{label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{label:'U.S. GAO Assessing Data Reliability',url:'https://www.gao.gov/products/gao-20-283g'},{label:'National Archives records management guidance',url:'https://www.archives.gov/records-mgmt'},{label:'HHS HIPAA Security Rule guidance',url:'https://www.hhs.gov/hipaa/for-professionals/security/index.html'},{label:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'}] as const;
const researchTopics=[
['exception-reopen-rate-definition-research','How Often Does a Completed Service Exception Reopen Under One Fixed Rule?','exception reopen rate','the count of eligible closed exceptions reopened within the declared observation window'],
['source-record-field-concordance-research','Do Copied Operations Fields Match Their Declared Source Records?','source-record field concordance','field-level agreement between the frozen work record and its linked source'],
['approval-queue-decision-latency-research','How Long Do Bounded Approval Requests Wait for an Owner Decision?','approval queue decision latency','elapsed time from a complete request timestamp to the recorded owner decision'],
['least-privilege-access-exception-research','Which Active Service Accounts Exceed the Permissions in Their Task Map?','least-privilege access exceptions','documented permission differences between active accounts and the approved task map'],
['handoff-blocker-resolution-path-research','Can Reviewers Trace a Blocked Handoff to Its Resolution Owner?','handoff blocker resolution paths','the share of eligible blocked items with a named owner, dated next action, and final state']
] as const;
export const september11ResearchPosts=researchTopics.map(([slug,title,focus,measure])=>({slug,title,published,excerpt:`A bounded study protocol for ${focus}, with source rules, reviewer checks, and explicit limits on what the result can support.`,thumbnail:'/research-thumbnails/research-batch-2026-08-10.svg',headlineStat:`One pre-registered measure: ${measure}`,methodology:`Methodology: define one eligible ${focus} queue before looking at outcomes. Freeze the observation period, fields, exclusions, reviewer instructions, and the rule for ${measure}. Include every eligible record or document the random selection method. Two reviewers score the same records independently and preserve disagreements. Report exact counts, denominators, missing evidence, exclusions, and unscorable cases.`,sources,related:[],body:[
`Research question and scope: ${title} The study covers one named workflow, one approved system of record, one fixed period, and the people authorized to review ${focus}. It excludes other clients, providers, teams, and periods.`,
`The observation unit is one eligible record from the frozen queue. The primary measure is ${measure}. Define pass, failure, and unscorable results before sampling. Keep later corrections separate from the state visible at the cutoff.`,
'NIST CSF 2.0 informs governance and access questions. The NIST Privacy Framework informs purpose and data minimization. GAO guidance supports testing whether data are fit for the stated use. National Archives guidance supports record identity and retrieval. HHS guidance applies only when a scoped workflow contains protected health information. These sources shape the protocol; they do not supply a client result.',
'Publish the eligible population, observed count, category counts, reviewer agreement, missing-source count, and exclusions. Use counts for small groups. A missing field is not evidence of poor worker performance when access, system design, or upstream inputs may explain it.',
'Inference boundary: the study can describe selected records under frozen definitions. It cannot establish causation, rank workers, certify compliance, estimate savings, compare vendors, or predict another workflow.',
'Limitations include changing permissions, incomplete system histories, reviewer interpretation, an unrepresentative queue, and later evidence that changes a record after the observation cutoff.',
'An accountable owner may use the result to test one field, label, link, access rule, or escalation change. Repeat the protocol on fresh records before expansion. Do not use it for covert monitoring or automated employment action.',
'References: the numbered links below are primary government or standards-program sources. They support the control concepts, not a performance claim. Local legal, clinical, security, policy, and personnel decisions remain with authorized owners.'
],faq:[{question:'What does this study establish?',answer:'Only the observed counts for the declared queue, period, definitions, and evidence available at the cutoff.'},{question:'What does it not establish?',answer:'It does not prove causation, compliance, individual performance, provider quality, savings, or a result that transfers to another workflow.'}]}));
