const published='2026-09-10' as const;
const image='/filipino-service-workflow.svg' as const;
const blogTopics=[
['insurance-certificate-renewal-desk','Run an Insurance Certificate Renewal Desk Without Judging Coverage','insurance certificate renewals','vendor, certificate type, source file, expiry date, request state, and risk owner','coverage limits, exclusions, or whether a certificate is acceptable','expired files, incorrect dates, unanswered requests, and unresolved owner decisions'],
['legal-matter-document-intake-queue','Organize a Legal Matter Document Intake Queue Without Giving Legal Advice','legal matter document intake','matter ID, received date, sender, original filename, source location, and assigned counsel','relevance, privilege, legal deadlines, or document meaning','misfiled originals, broken links, unclear matter IDs, and questions awaiting counsel'],
['food-supplier-specification-change-log','Track Food Supplier Specification Changes Without Approving the Product','food supplier specification changes','supplier, item code, version, effective date, prior version, and technical reviewer','allergen, safety, labeling, regulatory, or acceptance questions','missed changes, wrong versions, absent source files, and late technical reviews'],
['commercial-property-work-order-closeout','Close Out Commercial Property Work Orders With Verifiable Evidence','commercial property work-order closeout','property, work-order ID, required evidence, vendor update, tenant notice, and manager','safety, workmanship, cost disputes, scope changes, or tenant complaints','unsupported closures, missing photos, reopened orders, and overdue manager checks'],
['clinical-trial-site-file-reconciliation','Reconcile a Clinical Trial Site File Without Making Clinical Decisions','clinical trial site-file reconciliation','study, site, expected document, version or date, approved location, and study owner','consent, eligibility, safety, protocol interpretation, or regulatory classification','false missing flags, wrong versions, misplaced records, and access blocks'],
['utility-bill-account-allocation-review','Prepare Utility Bill Allocations Without Posting the Accounting Entry','utility bill allocation preparation','supplier, service account, location, billing period, invoiced amount, and mapping source','coding, accruals, tax treatment, posting dates, or payment approval','stale mappings, transposed amounts, possible duplicates, and finance corrections'],
['museum-collection-loan-record-check','Check Museum Collection Loan Records Before a Handoff','museum collection loan records','object ID, agreement, condition-report state, transport record, return date, and registrar','object condition, handling requirements, contract meaning, or permission to transport','missing reports, conflicting dates, restricted images, and registrar decisions'],
['telecom-circuit-inventory-validation','Validate a Telecom Circuit Inventory Before Renewal Review','telecom circuit inventory validation','carrier circuit ID, site, service label, billing account, contract, and operational owner','whether a circuit is unused, should be disconnected, or should accept new terms','unmatched bills, unknown sites, conflicting identifiers, and missing contracts'],
['subscription-entitlement-change-queue','Manage a Subscription Entitlement Change Queue With Approval Boundaries','subscription entitlement changes','requester, account, current entitlement, requested state, approval, and effective date','discounts, credits, contract changes, unusual access, or disputed requests','failed changes, missing approvals, state mismatches, and customer notices still due'],
['public-records-request-intake-register','Maintain a Public Records Request Intake Register Without Deciding Disclosure','public records request intake','received timestamp, original request text, approved identifier, coordinator, source, and official status','disclosure, exemptions, legal deadlines, fees, or redactions','timestamp errors, changed request text, missing owners, and decisions without evidence'],
['aviation-maintenance-record-indexing','Index Aviation Maintenance Records Without Releasing an Aircraft','aviation maintenance record indexing','aircraft or component ID, record type, event date, revision, source, and issuer as shown','airworthiness, release to service, technical applicability, or regulatory meaning','wrong associations, unreadable files, identifier conflicts, and maintenance corrections'],
['franchise-location-opening-checklist','Coordinate a Franchise Location Opening Checklist Without Approving Readiness','franchise location opening coordination','location, workstream, evidence requirement, due date, dependency, and accountable owner','permits, safety, employment, spending, brand exceptions, or the final opening decision','unsupported completions, hidden dependencies, late evidence, and owner decisions still open']
] as const;
export const september10BlogPosts=blogTopics.map(([slug,title,focus,fields,boundary,review],index)=>({slug,title,published,image,minutes:8+(index%3),excerpt:`A Philippines-based support routine for ${focus}, with source evidence and decisions kept with accountable owners.`,body:[
`${title} starts with a narrow administrative question: is the expected record present, identifiable, current, and routed to the right person? The specialist prepares evidence. An authorized owner makes any consequential decision.`,
`Use one approved register containing ${fields}. Copy source values as written and link the native record. If two sources disagree, preserve both values and mark the conflict instead of quietly choosing one.`,
`The specialist must escalate ${boundary}. Missing permission is also an exception. It is not permission to download sensitive material, use a personal account, or move records into an open folder.`,
`Keep ready, missing evidence, source conflict, and owner review as separate states. Administrative completeness must not look like technical, financial, legal, clinical, safety, or policy approval.`,
`Check a recurring sample against the original records. Count ${review} separately so the manager can see whether the routine, access model, upstream source, or approval path needs repair.`,
`The handoff lists completed records, blocked items, the exact question on each exception, and its next owner. That is the finish line for the support lane; approval remains outside it.`]}));
const sources=[{label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{label:'U.S. GAO Assessing Data Reliability',url:'https://www.gao.gov/products/gao-20-283g'},{label:'National Archives records management guidance',url:'https://www.archives.gov/records-mgmt'},{label:'HHS HIPAA Security Rule guidance',url:'https://www.hhs.gov/hipaa/for-professionals/security/index.html'},{label:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'}] as const;
const researchTopics=[
['exception-queue-age-definition-study','When Does an Outsourced Exception Queue Actually Become Old?','exception queue age','the timestamp that starts and stops elapsed time'],
['source-link-retrieval-reliability-study','Can a Second Reviewer Retrieve the Source Behind a Completed Update?','source-link retrieval','successful retrieval under a fixed time limit'],
['handoff-status-language-agreement-study','Do Two Reviewers Read Handoff Status Labels the Same Way?','handoff status language','independent agreement on one frozen label set'],
['least-privilege-task-access-study','Which Assigned Tasks Lack a Matching Least-Privilege Access Rule?','task-to-access mapping','documented task, permission, and approval-owner matches'],
['record-correction-traceability-study','Can Reviewers Reconstruct Why an Operations Record Was Corrected?','record correction traceability','a linked source, prior value, reason, actor, and review state']
] as const;
export const september10ResearchPosts=researchTopics.map(([slug,title,focus,measure])=>({slug,title,published,excerpt:`A bounded study protocol for ${focus}, with source rules, reviewer checks, and explicit limits on what the result can support.`,thumbnail:'/research-thumbnails/research-batch-2026-08-10.svg',headlineStat:`One pre-registered measure: ${measure}`,methodology:`Methodology: define one eligible ${focus} queue before looking at outcomes. Freeze the observation period, fields, exclusions, reviewer instructions, and the rule for ${measure}. Include every eligible record or document the random selection method. Two reviewers score the same records independently and preserve disagreements. Report exact counts, denominators, missing evidence, exclusions, and unscorable cases.`,sources,related:[],body:[
`Research question and scope: ${title} The study covers one named workflow, one approved system of record, one fixed period, and the people authorized to review ${focus}. It excludes other clients, providers, teams, and periods.`,
`The observation unit is one eligible record from the frozen queue. The primary measure is ${measure}. Define pass, failure, and unscorable results before sampling. Keep later corrections separate from the state visible at the cutoff.`,
'NIST CSF 2.0 informs governance and access questions. The NIST Privacy Framework informs purpose and data minimization. GAO guidance supports testing whether data are fit for the stated use. National Archives guidance supports record identity and retrieval. HHS guidance applies only when a scoped workflow contains protected health information. These sources shape the protocol; they do not supply a client result.',
'Publish the eligible population, observed count, category counts, reviewer agreement, missing-source count, and exclusions. Use counts for small groups. A missing field is not evidence of poor worker performance when access, system design, or upstream inputs may explain it.',
'Inference boundary: the study can describe selected records under frozen definitions. It cannot establish causation, rank workers, certify compliance, estimate savings, compare vendors, or predict another workflow.',
'Limitations include changing permissions, incomplete system histories, reviewer interpretation, an unrepresentative queue, and later evidence that changes a record after the observation cutoff.',
'An accountable owner may use the result to test one field, label, link, access rule, or escalation change. Repeat the protocol on fresh records before expansion. Do not use it for covert monitoring or automated employment action.',
'References: the numbered links below are primary government or standards-program sources. They support the control concepts, not a performance claim. Local legal, clinical, security, policy, and personnel decisions remain with authorized owners.'
],faq:[{question:'What does this study establish?',answer:'Only the observed counts for the declared queue, period, definitions, and evidence available at the cutoff.'},{question:'What does it not establish?',answer:'It does not prove causation, compliance, individual performance, provider quality, savings, or a result that transfers to another workflow.'}]}));
