type Seed=[string,string,string,string[]];
const blogs:Seed[]=[
['daily-delegated-work-intake-check','A Daily Intake Check for Delegated Work','Confirm source, finish line, priority, and decision owner before delegated work begins.',['Review new requests against an approved source and observable output. Vague requests stay in clarification.','Assign priority from written rules, verify narrow access, and name an owner for blockers.','Separate specialist actions from owner decisions, then count ready, blocked, and unclear work.']],
['virtual-assistant-recurring-task-register','Build a Recurring Task Register for a Virtual Assistant','Make cadence, source records, completion evidence, and backup ownership visible.',['Record each recurring task’s purpose, trigger, source, output, and accountable owner.','Use precise triggers and native completion evidence, with a pause condition for missing inputs.','Review after tool or owner changes and retire obsolete routines with a change note.']],
['shared-inbox-owner-decision-lane','Create an Owner-Decision Lane in a Shared Inbox','Keep sensitive messages visible without asking an assistant to infer authority.',['Define legal, security, payment, contract, and out-of-template messages that require judgment.','Link the source record, deadline, and exact decision while retaining content in the approved inbox.','Assign an owner and review time, then close the item with its decision and message reference.']],
['delegated-data-entry-source-check','A Source Check Before Delegated Data Entry','Prevent incomplete or conflicting inputs from becoming authoritative records.',['Name the authoritative source for each field group and test completeness and identifiers.','Preserve conflicting approved references and route the choice to the data owner.','Apply field and duplicate checks, then retain the batch, source version, and completion time.']],
['assistant-meeting-action-register','Turn Meeting Notes into an Action Register','Convert approved meeting outcomes into owners, due dates, evidence, and escalation points.',['Separate approved decisions, actions, questions, and background before creating tasks.','Give each observable action one owner and only a due date that participants agreed.','Route sensitive commitments through existing approvals and close actions with evidence.']],
['virtual-assistant-template-control-log','Control Message Templates Used by Virtual Assistants','Show which replies are approved, where they apply, and who owns their review.',['Give templates a purpose, audience, owner, version date, and approved location.','Mark editable fields and exclusions such as complaints, refunds, and uncertain accounts.','Archive replaced versions and sample both the wording and its classification in actual use.']],
['outsourced-queue-aging-review','Run a Queue Aging Review for Outsourced Work','Distinguish ordinary processing from blocked work and forgotten exceptions.',['Set age bands suited to the service and record the last meaningful action on old items.','Separate waits on specialists, customers, systems, and internal decisions; escalate by risk.','Preserve history and use recurring patterns to repair intake, ownership, or instructions.']],
['assistant-file-delivery-checklist','A File Delivery Checklist for Assistant-Created Reports','Confirm source, period, formulas, permissions, filename, and approval before delivery.',['Verify the approved export and period, then test formulas, filters, totals, and units.','Use the agreed filename and approval status, removing public or unnecessary access.','Deliver the source, period, known exceptions, and approval state without duplicating the report.']],
['delegated-customer-record-merge-rule','Write a Safe Customer Record Merge Rule','Identify likely duplicates while reserving irreversible merges for controlled approval.',['Define strong match evidence and compare identifiers, linked activity, and permissions.','Prohibit automatic merges for conflicts, disputes, separate entities, or unclear primary records.','After authorized action, verify linked work and retain the merge audit reference.']],
['virtual-assistant-absence-coverage-note','Prepare an Absence Coverage Note for a Virtual Assistant','Protect deadlines, decisions, access boundaries, and ownership during planned leave.',['List only work due during leave, with state, source, deadline, and next owner.','Give backups their own approved access and pause low-risk routines that can safely wait.','On return, reconcile actions and blockers before closing temporary coverage ownership.']],
['assistant-weekly-capacity-conversation','Hold a Weekly Capacity Conversation with an Assistant','Compare committed work, new demand, waiting time, and quality before priorities collide.',['Review named tasks and deadlines rather than relying on unsupported utilization percentages.','Examine source waits, rework, questions, approvals, and quality beside completed volume.','When demand exceeds time, the manager chooses and records the accepted tradeoff.']],
['delegated-work-completion-evidence','Define Completion Evidence for Delegated Tasks','Verify completion without screenshots, duplicate reports, or constant supervision.',['Choose a native status, record link, transaction identifier, or accepted file for each task.','Do not mistake time spent, messages sent, or documents opened for a finished outcome.','Avoid copied sensitive evidence and revise definitions when reviewers cannot reproduce results.']]
];
export const september2BlogPosts=blogs.map(([slug,title,excerpt,body],i)=>({slug,title,excerpt,body,minutes:8+i%4,published:'2026-09-02' as const}));
const research:Seed[]=[
['delegated-work-arrival-pattern-study','Study Design: Measuring Arrival Patterns in a Delegated Work Queue','Separate request arrival, due-time pressure, and batching effects before staffing decisions.',['Question: when does work enter the queue, and how does that differ from its requested due time?','Method: collect native timestamps, category, channel, and ready-for-work time for a predefined period.','Limitation: the chosen period bounds results; repeat observations before testing intake or coverage changes.']],
['assistant-rework-classification-method','Method Note: Classifying Rework in Assistant-Handled Tasks','Separate source defects, instruction gaps, execution errors, and changed decisions.',['Question: what observable conditions cause a completed delegated task to reopen?','Method: retain instruction version, source, first output, reviewer finding, and correction.','Limitation: reviewed items alone support targeted tests, not universal performance conclusions.']],
['owner-decision-wait-time-observation','An Observation Protocol for Owner-Decision Wait Time','Measure complete-escalation wait time without blaming either side.',['Question: how long is work paused after a complete decision request reaches an owner?','Method: capture escalation readiness, category, risk, substantive response, and restart time.','Limitation: timestamps do not explain delay; test packets or backups without creating surveillance.']],
['delegated-task-instruction-findability-test','Usability Test: Can Assistants Find the Right Task Instruction?','Measure whether specialists can locate the approved instruction and version.',['Question: can a specialist find the correct routine and exception rule without informal memory?','Method: observe searches, dead ends, version selection, and help requests in fixed scenarios.','Limitation: familiarity and access affect results; repair navigation and retest bounded tasks.']],
['queue-exception-recurrence-review','Research Framework: Reviewing Recurring Queue Exceptions','Preserve differences between exception frequency, severity, and business impact.',['Question: which documented exceptions recur, and where do they enter the workflow?','Method: deduplicate records and code first condition, stage, source, owner, and resolution.','Limitation: only recognized exceptions appear; test one control hypothesis against a preserved baseline.']]
];
export const september2ResearchPosts=research.map(([slug,title,excerpt,body])=>({slug,title,excerpt,body,published:'2026-09-02' as const,image:'/research-thumbnails/research-batch-2026-08-10.svg'}));
