type S={published:'2026-09-03',slug:string,title:string,question:string,unit:string,fields:string,confounder:string,decision:string,sources:{label:string,url:string}[]};
const sources=[{label:'ISO 9001 quality management systems',url:'https://www.iso.org/iso-9001-quality-management.html'},{label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{label:'U.S. National Archives records management guidance',url:'https://www.archives.gov/records-mgmt'},{label:'CISA Cybersecurity Performance Goals',url:'https://www.cisa.gov/cybersecurity-performance-goals'},{label:'W3C Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'}];
const items:S[]=[
{published:'2026-09-03',slug:'philippines-escalation-packet-completeness-study',title:'Do complete escalation packets shorten decision waits in Philippines service teams?',question:'Does a packet with the source record, current state, exact decision, deadline, and named owner reduce safe restart time?',unit:'one escalation that stops or redirects delegated work',fields:'field presence, working-time wait, missing-information return, risk class, owner response, and safe restart',confounder:'case risk, owner availability, time-zone overlap, and specialist experience',decision:'whether to adopt the five-field packet in the studied service lane',sources:sources.slice(0,4)},
{published:'2026-09-03',slug:'outsourced-queue-status-consistency-research',title:'How consistently do outsourced specialists classify queue status?',question:'Do specialists assign the same ready, waiting, blocked, and owner-decision state to the same facts?',unit:'one independently classified, redacted queue scenario',fields:'selected state, stated reason, missing facts, disagreement pair, task family, and classification time',confounder:'scenario wording, familiarity, dominant labels, and production context absent from an exercise',decision:'whether to clarify, merge, or retire queue states',sources:sources.slice(0,3)},
{published:'2026-09-03',slug:'service-quality-reviewer-agreement-study',title:'When do quality reviewers disagree on delegated service work?',question:'Where do two independent reviewers diverge when applying a frozen quality rubric to the same delegated work?',unit:'one criterion scored against one sampled work record',fields:'rubric version, independent scores, cited evidence, severity, unscorable state, and adjudication',confounder:'sample composition, reviewer familiarity, ambiguous policy, and seniority during adjudication',decision:'whether the rubric is reliable enough for coaching or operational decisions',sources:sources.slice(0,3)},
{published:'2026-09-03',slug:'virtual-assistant-knowledge-retrieval-friction-study',title:'What causes knowledge-retrieval friction for virtual assistants?',question:'Can an assistant find the current instruction, approved example, accountable owner, and exception rule?',unit:'one fixed retrieval scenario completed with production-equivalent access',fields:'search terms, navigation path, dead ends, help requests, version choice, accuracy, and elapsed time',confounder:'prior familiarity, personalized search, permission differences, and think-aloud delay',decision:'which naming, linking, versioning, or access repair to test',sources:[sources[2],sources[4],sources[0],sources[1]]},
{published:'2026-09-03',slug:'delegated-work-interruption-recovery-research',title:'How should delegated teams measure interruption recovery?',question:'After interruption, how long until a specialist reaches the next valid source-linked action?',unit:'one interruption and its recovery sequence in an active delegated task',fields:'active work, external waiting, interruption, recovery, task family, priority change, and checkpoint use',confounder:'task complexity, urgent events, self-report error, seasonal demand, and time-zone overlap',decision:'which focus protection or checkpoint change deserves a controlled retest',sources:[sources[0],sources[1],sources[3],sources[2]]}
];
const body=(x:S)=>[
'Research question: '+x.question+' This is narrow and operational. It concerns a Philippines-based outsourced service lane, not the character, intelligence, or motivation of an individual worker. The accountable business owner keeps authority over policy, customer commitments, security, finance, and exceptions. The study asks whether a defined part of the work system can be observed well enough to support one bounded management decision.',
'Scope and unit: the unit of analysis is '+x.unit+'. Before observation, the owner writes inclusion and exclusion rules, fixes the window, names the systems of record, and defines the events that start and stop measurement. Routine work outside that definition does not drift into the sample. Sensitive customer details stay in approved systems; the research record uses stable references and only the fields required to reproduce classification.',
'Method: collect '+x.fields+'. Use native task, ticket, document, or audit events where they truthfully represent the action. A short structured observation note may add context that timestamps cannot show, but recollection should not replace system evidence. Select the stopping rule before viewing results. Preserve ordinary cases, boundary cases, and exceptions rather than choosing only tidy records that support a preferred conclusion.',
'Evidence basis: ISO 9001 supports defined criteria, controlled processes, and retained evidence. NIST CSF 2.0 and CISA guidance support governed ownership and response paths. National Archives guidance supports retrievable, versioned records, while WCAG 2.2 supplies useful principles when an interface is part of the question. These sources inform control design. None proves a performance effect for OutsourcedService.com, a customer, or the Philippines outsourcing market.',
'Facts and analysis remain separate. Recorded timestamps, present fields, selected labels, source versions, and reviewer actions are observations. Any claim about why a pattern occurred is analysis. The report places the relevant count or sequence beside each interpretation and offers plausible alternatives. A repeated pattern can justify a small workflow test; it does not establish motive, causation, or a universal benchmark. Null and mixed results remain reportable.',
'Analysis displays exact counts, the observed range, and medians where the sample supports them. Small groups should not become impressive-looking percentages. Break results out by task family and risk class when those conditions change meaning. Do not collapse waiting, active work, approval, or exception handling into one efficiency number. A faster result is not necessarily better if it bypasses review, conceals a reopened item, or weakens source traceability.',
'The main threats to interpretation are '+x.confounder+'. Record these conditions where possible and state them plainly where they cannot be controlled. A phased change or fresh parallel scenario can strengthen a follow-up test, although random assignment may be unsafe for urgent work. Findings apply to the observed lane, people, tools, definitions, and period. They do not support public claims about savings, accuracy, staffing ratios, or service levels.',
'Human boundaries matter. The exercise must not become covert surveillance or automatic performance ranking. Managers own the quality of instructions, access, source precedence, decision routes, and review criteria. Specialists can identify ambiguity and document exceptions without silently rewriting policy. When evidence is missing, the honest result is unscorable or unresolved. Forcing certainty into a score hides the operating defect that the research should reveal.',
'Validation requires a second pass. Another reviewer reproduces sample selection, locates the cited source, applies frozen definitions, and verifies counts. Corrections remain visible with reason and approver. After one approved process change, repeat the observation with comparable fresh cases. Success means improvement on the target condition without worse quality, missed deadlines, unresolved risk, or customer harm. Otherwise revert the change or revise the hypothesis before a wider rollout.',
'Practical use: the output is a decision record, not a generic checklist. It shows the question, method, included records, exclusions, observations, interpretations, limitations, and named owner. The immediate choice is '+x.decision+'. If evidence is weak, improve the study before expanding the rule. If evidence is credible, change only the studied lane, explain the boundary to the team, and schedule a bounded retest.',
'Limitations: one window cannot capture every demand pattern, rare event, tool change, or working relationship. People may behave differently while observed. Records can omit offline conversation, and definitions can privilege their author. De-identification may remove context needed for some judgments. These limits do not make the study useless; they set the claim size. The published conclusion must stay within what preserved evidence can support.',
'Decision review should also test reversibility. The owner records what would cause the change to be paused or rolled back, who will inspect the next sample, and when the evidence will be reconsidered. This guards against a short observation becoming permanent policy by inertia. It also gives specialists a clear route for reporting a new exception without changing the rule themselves.',
'Operational context must stay visible. A result from routine administrative work may not transfer to complaints, payments, privacy requests, security events, or contractual decisions. Those lanes can require different evidence and approval. The report names excluded work and preserves the distinction between a process observation and a business judgment. Readers should be able to tell exactly where the proposed change applies and where it does not.',
'Evidence-led conclusion: this method can support '+x.decision+' when the team preserves definitions, source evidence, alternative explanations, and a follow-up test. It cannot prove general provider quality or individual productivity. For a Philippines-based service operation, its value is practical: it makes one disputed part of the workflow observable, leaves consequential judgment with the owner, and creates a record another reviewer can challenge or reproduce before work changes.'
];
export const september3ResearchPosts=items.map(x=>({slug:x.slug,title:x.title,excerpt:'A bounded field study asking: '+x.question,published:'2026-09-03' as const,thumbnail:'/research-thumbnails/research-batch-2026-08-10.svg',headlineStat:'12-part evidence protocol',methodology:'A prospective, bounded observation using frozen definitions and native records. Findings apply only to the stated lane and period.',sources:x.sources,related:[],faq:[{question:'What should managers verify first?',answer:'Verify the question, unit, definitions, source records, window, and decision owner.'},{question:'What does the study not prove?',answer:'It does not prove individual productivity, provider quality, or a universal benchmark.'}],body:body(x)}));
